### ISSUE TITLE
Cannot perform training on the Promise12 dataset

### ISSUE THREAD

**Issue by amh28** [NifTK/NiftyNet#10]
Hello, I am trying to run the demo:

`python net_segment.py train --conf demos/PROMISE12/promise12_demo_train_config.ini --max_iter 10`

 but apparently it cannot load the Promise12 images in .mhd format since It is giving me the following error: 

File "/home/alemh/anaconda2/envs/nifty_env/lib/python3.5/site-packages/niftynet/io/misc_io.py", line 80, in load_image
    'No loader could load the file')  # Throw last error
nibabel.filebasedimages.ImageFileError: No loader could load the file

Do you have any insights on how to solve this? Any help would be appreciated

**Comment by wyli** [comment]
Hi @amh28 , for this demo SimpleITK is required, usually it can be installed by `pip install SimpleITK`. I'm closing this issue now but please feel free to reopen or ask questions on StackOverflow niftynet tag https://stackoverflow.com/questions/tagged/niftynet.

**Comment by amh28** [comment]
Hello, thank you that problem was solved installing SimpleITK as you said, but now it gives me the following error: 

Traceback (most recent call last):
  File "net_segment.py", line 8, in <module>
    sys.exit(main())
  File "/home/amarquez/aa/NiftyNet/niftynet/__init__.py", line 114, in main
    app_driver.initialise_application(system_param, input_data_param)
  File "/home/amarquez/aa/NiftyNet/niftynet/engine/application_driver.py", line 168, in initialise_application
    data_split_file=system_param.dataset_split_file)
  File "/home/amarquez/aa/NiftyNet/niftynet/io/image_sets_partitioner.py", line 86, in initialise
    self.load_data_sections_by_subject()
  File "/home/amarquez/aa/NiftyNet/niftynet/io/image_sets_partitioner.py", line 181, in load_data_sections_by_subject
    modality_file_list = self.grep_files_by_data_section(section_name)
  File "/home/amarquez/aa/NiftyNet/niftynet/io/image_sets_partitioner.py", line 244, in grep_files_by_data_section
    match_and_write_filenames_to_csv([matcher], csv_file)
  File "/home/amarquez/aa/NiftyNet/niftynet/utilities/util_csv.py", line 221, in match_and_write_filenames_to_csv
    KeywordsMatching.matching_subjects_and_filenames(c)
  File "/home/amarquez/aa/NiftyNet/niftynet/utilities/filename_matching.py", line 87, in matching_subjects_and_filenames
    self.__dict__))
IOError: no file matched based on this matcher: {'path_to_search': ('/home/amarquez/aa/NiftyNet/data/PROMISE12/TrainingData_Part1',), 'filename_contains': (u'Case', u'_segmentation', u'mhd'), 'filename_not_contains': (u'Case2',)}


My config file is the following:

#path_to_search = data/PROMISE12/TrainingData_Part1,data/PROMISE12/TrainingData_Part2,data/PROMISE12/TrainingData_Part3
path_to_search = data/PROMISE12/TrainingData_Part1
filename_contains = Case,mhd
filename_not_contains = Case2,segmentation
spatial_window_size = (64, 64, 64)
interp_order = 3
axcodes=(A, R, S)

[label]
#path_to_search = data/PROMISE12/TrainingData_Part1,data/PROMISE12/TrainingData_Part2,data/PROMISE12/TrainingData_Part3
path_to_search = data/PROMISE12/TrainingData_Part1
filename_contains = Case,_segmentation,mhd
filename_not_contains = Case2
spatial_window_size = (64, 64, 64)
interp_order = 3
axcodes=(A, R, S)

############################## system configuration sections
[SYSTEM]
cuda_devices = ""
num_threads = 2
num_gpus = 1
model_dir = ./promise12_model

[NETWORK]
name = dense_vnet
activation_function = prelu
batch_size = 1

# volume level preprocessing
volume_padding_size = 0
# histogram normalisation
histogram_ref_file = standardisation_models.txt
norm_type = percentile
cutoff = (0.01, 0.99)
normalisation = True
whitening = True
normalise_foreground_only=True
foreground_type = otsu_plus
multimod_foreground_type = and
window_sampling = resize

queue_length = 8


[TRAINING]
sample_per_volume = 4
rotation_angle = (-10.0, 10.0)
scaling_percentage = (-10.0, 10.0)
random_flipping_axes= 1
lr = 0.00002
loss_type = Dice
starting_iter = 0
save_every_n = 12500
max_iter = 25000
max_checkpoints = 20

############################ custom configuration sections
[SEGMENTATION]
image = promise12
label = label
output_prob = False
num_classes = 2
label_normalisation = True
min_numb_labels = 2
min_sampling_ratio = 0.000001



I do not understand why this is happening since all the .mhd and .raw files are on the directory of the path_to_search variable in the config file.

Thanks in advance for the reply

**Comment by wyli** [comment]
The config looks ok (except it misses the first line as the one in the demo https://github.com/NifTK/NiftyNet/blob/dev/demos/PROMISE12/promise12_demo_train_config.ini#L1). 

Could you confirm your data folder structure is the same as the following:
```
data/PROMISE12/TrainingData_Part1
├── Case00.mhd
├── Case00.raw
├── Case00_segmentation.mhd
├── Case00_segmentation.raw
├── Case01.mhd
├── Case01.raw
├── Case01_segmentation.mhd
├── Case01_segmentation.raw
├── Case02.mhd
├── Case02.raw
├── Case02_segmentation.mhd
├── Case02_segmentation.raw
...
```
if the answer is yes but you still have this issue, I'll need more details of your system for debugging:

You could collect system information using TensorFlow's environment capture script:
https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

**Comment by amh28** [comment]
Hello, I have the exact same structure because I only downloaded the first part of the Promise12 dataset. I do not know why this is happening since I did not make any changes to the code and downloaded all the requirements from requirements-gpu.txt. Also **I am working inside an anaconda environment.**

Finally I am using a Tesla K80 with 11Gb of free memory and this is my  system information output using tf_env_collect.sh :

`== cat /etc/issue ===============================================
Linux n006 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== uname -a =====================================================
Linux n006 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.13.1)
protobuf (3.4.0)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.5)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.3.0
tf.GIT_VERSION = unknown
tf.COMPILER_VERSION = unknown
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-8.0/lib64
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Fri Nov 24 11:41:53 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:04:00.0     Off |                    0 |
| N/A   35C    P0    55W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:05:00.0     Off |                    0 |
| N/A   24C    P0    70W / 149W |      0MiB / 11439MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0.44
/usr/local/cuda-8.0/doc/man/man7/libcudart.7
/usr/local/cuda-8.0/doc/man/man7/libcudart.so.7
`

**Comment by wyli** [comment]
Hi @amh28 Thanks for the info, but I couldn't replicate this problem (with Python 2.7 or 3.6) using a very similar system environment to yours.

A few things to try/workaround:

1) does Python have access to the folder,
What's the outcome of this bash command?
```bash
python -c "import os; print(os.listdir('/home/amarquez/aa/NiftyNet/data/PROMISE12/TrainingData_Part1'))"
```
2) move the images to a new folder, and change `path_to_search` to the new folder.

3) skip the file name search and specifies input file lists using csv files (https://github.com/NifTK/NiftyNet/tree/dev/config#input-data-source-section).
