### ISSUE TITLE
About Sensitivity Specificity loss function implementation

### ISSUE THREAD

**Issue by amh28** [NifTK/NiftyNet#100]
Hello, I have a doubt about Sensitivity Specificity NiftyNet's implementation.
The Sensitivity coefficient by definition is the number of correctly segmented trues over all trues, and it is represented  by the proportion: 

**Sensitivity = (true_positives)/(true_positives+false_negatives)**

So I think that the correct way to translate this Sensitivity into **prediction ** and **ground_truth ** terms for a loss function would be similar to: 

**true_positives** = prediction*ground_truth
**false_negatives** = (1-prediction)*ground_truth

But in your implementation, you express Sensitivity in terms of :

**Sensitivity** = (square(ground_truth-prediction) * (1-one_hot) ) **/** (1-one_hot)

If I understand well, this formula is different from the Sensitivity definition, and it rather represents the proportion: (false_positives)/(false_positives+true_negatives).

The same occurs with the Specificity formula implementation, which I think differs from the definition:

**Specificity** = (true_negatives)/(true_negatives+false_positives)

Is there something I am missing? Maybe I am not giving these formulas the right interpretation. Any ideas would be of much help. Thanks

**Comment by wyli** [comment]
Hi @amh28 The loss function returns values that we want to _minimise_. But I agree that the variable names are slightly misleading, they are actually "sensitivity errors" and "specificity errors"

**Comment by amh28** [comment]
Hi @wyli , thanks for the answer. However, I am still confused about sensitivity and specificity "error" implementations. 

For example, if the Sensitivity coefficient is calculated by : truepos/(truepos+falseneg), why don't you simply calculate it by: (prediction*one_hot)/(one_hot).

Thanks for the help.
