### ISSUE TITLE
Bring repo up to recommended community standards

### ISSUE THREAD

**Issue by dzhoshkun** [NifTK/NiftyNet#102]
[Some elements of the recommended community standards are missing](https://github.com/NifTK/NiftyNet/community).
It might be worth considering providing these elements, which could be helpful in terms of the workflow.
GitHub even provides off-the-shelf templates for some.

**Comment by fepegar** [comment]
I wonder why GitHub says that NiftyNet is missing an [issue template](https://github.com/NifTK/NiftyNet/blob/dev/.github/ISSUE_TEMPLATE.md).
