### ISSUE TITLE
Can somebody explain the interaction of config parameters spatial_window_size, volume_padding_size, border, loss_border

### ISSUE THREAD

**Issue by anlarro** [NifTK/NiftyNet#103]
When doing regression, how does config parameters spatial_window_size, volume_padding_size, border, loss_border interact in order to generate the final inferenced image? I have changed these values but still I can't get a clear image. They appear either with stripes or with too much border.

Thanks!

**Comment by Zach-ER** [comment]
Hi there, 
`volume_padding_size` is how much padding is added to an image when it's loaded in. This one is 
probably not causing your problem. 
`spatial_window_size` is the size of a patch to take from the whole image. 
`border` is how much of the patch to ignore when doing inference. In other words, it controls how much overlap each inference patch has. The final result at a given voxel will be given by an inference iteration where that pixel was in the centre (not in the border). 
`loss_border` should only affect training. It defines a border within which the loss function is unaffected by the network's output. 

In general I have found that having a large `border` helps the smoothness of my results. Hope this helps!

**Comment by 1160914483** [comment]
Hello, is the sample_per_volume value the number of patches mentioned in spatial_window_size?
Thank!

**Comment by Zach-ER** [comment]
@1160914483 yes, it is the number of patches taken from each entire volume that is loaded in.
