### ISSUE TITLE
Failed to import the custom network

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#104]
I think that I followed the instructions: create a new directory 'newNet' and place it inside the 'niftynet/extensions/' with 2 files: __init__.py and newNet.py. But still I got this error:

> ValueError: Could not import network: Incorrect module name "newNet"; expected "module.object".

More info: the path for the model in the config file is: models/newNet

Any help would be appreciated!!

**Comment by wyli** [comment]
Hi @YilinLiu97 for a concrete example of loading `/home/dev/mymodules/mynetwork.py` (assuming the network `class NewNet(...):` defined in this `.py` file)

1. make the folder on the `$PYTHONPATH`:
`export PYTHONPATH=/home/dev/:$PYTHONPATH`

2. make `mymodules` a python path:
create an empty `__init__.py` file in `/home/dev/mymodules/`

3. run NiftyNet with a configure file, in which we specify the new network in the `[NETWORK]` section:
`name = mymodules.mynetwork.NewNet`

NiftyNet will decode the `name` string as a python command:
`from mymodules.mynetwork import NewNet`
