### ISSUE TITLE
How to implement cross-validation in config file?

### ISSUE THREAD

**Issue by anlarro** [NifTK/NiftyNet#110]
Hi,

Is there an easy way to implement cross-validation in Niftynet by specifying the "dataset_split_file" in the config file? 

Thanks.

**Comment by wyli** [comment]
Hi @anlarro, the simplest way would be, for example for a 3-fold CV:

1.  Getting an initial `test_split.csv` by running an automatic random splitting:
```bash
python net_segment.py train... --exclude_fraction_for_validation 0.1 \
        --exclude_fraction_for_inference 0.1
        --dataset_split_file test_split.csv
```

Content of the generated `test_split.csv` in `[model_dir]` should be pairs of "[subject_id],  [phase]":
```csv
subject_1,Training
subject_2,Validation
subject_3,Inference
...
```
2.  Make 3 copies of `test_split.csv`, e.g. `test_split_fold_1.csv`, `test_split_fold_2.csv`, `test_split_fold_3.csv` and modify the phase value of each subject in the files accordingly.

3.  Run training/inference for each fold by: 
```
python net_segment.py ... --dataset_split_file test_split_fold_1.csv 
```
```
python net_segment.py ... --dataset_split_file test_split_fold_2.csv 
```
```
python net_segment.py ... --dataset_split_file test_split_fold_3.csv 
```
