### ISSUE TITLE
input size for deep medic 

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#112]
I'm wondering why cropping the inputs from 57 to 27 instead of directing extracting patches of size 27x27x27? Thanks.

**Comment by wyli** [comment]
Hi @YilinLiu97,  that was initially implemented with an early version of tensorflow, there wasn't a proper `tf.slice` function back then.  The crop layer is actually 'extracting' patches since https://github.com/NifTK/NiftyNet/commit/984d17836d7a6240942cd44f2f61c92a427bb9bb.
