### ISSUE TITLE
Activation visualization

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#116]
Hi, is there any suggestion for implementing the visualization of activation in Niftynet? Thanks!

**Comment by wyli** [comment]
Hi @YilinLiu97 at the moment there are two options:
* in your network implementation adding visusalisations to tensorboard, for example in `dense_vnet`: https://github.com/NifTK/NiftyNet/blob/v0.3.0/niftynet/network/dense_vnet.py#L285

* change your network to return the activation map to here:
https://github.com/NifTK/NiftyNet/blob/v0.3.0/niftynet/application/segmentation_application.py#L364 and modify `interpret_output`function (https://github.com/NifTK/NiftyNet/blob/v0.3.0/niftynet/application/segmentation_application.py#L387) to save the numpy array to some file.

**Comment by nguyenhg** [comment]
Hi @wyli,
Can we print the activation map of a VAE layer (in training), e.g: the last layer of encoding? Thank you.

**Comment by mmodat** [comment]
Not sure what is meant by print but should it help you can visualise the activation maps as scalar images in tensorboard using the image summary as defined here https://github.com/NifTK/NiftyNet/blob/0f0d73670ac5e9892619004da3108deacecc75c7/niftynet/engine/application_variables.py#L20
