### ISSUE TITLE
NotImplemented error

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#117]
Hi, I'm using the resnet for inference. 

[train]
spatial_window_size = (16,16,16)

[inference]
border = [5,5,5]
spatial_window_size = (8,8,8)

It gave me this error:

>   File "/home/yilinliu/Niftynet_copy/niftynet/engine/windows_aggregator_base.py", line 135, in crop_batch
    raise NotImplementedError
NotImplementedError

I've also tried [0,0,8] for the spatial_window_size and set border to [0,0,0]. None of them worked.

Any help is appreciated!

**Comment by Zach-ER** [comment]
The `border` is applied both sides of each dimension: I think this may mean you have negative dimensions for your inference. Try increasing the spatial window size or decreasing the border. Any luck?
