### ISSUE TITLE
weird segmentation output 

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#118]
Hi, I'm doing a 3 classes segmentation problem. The image below is the seg output I got. The grey part is the labelled as class 1 and the white part was labelled as class 2. I'm trying to segment some subcortical structures so this seg output is obviously bad but I'm wondering how is it possible that the class 1 was labelled so uniformly outside the brain?? btw I used the balanced sampler. Thanks!

![screenshot 2018-06-04 23 16 52](https://user-images.githubusercontent.com/26695815/40955088-7a71ec46-684d-11e8-8e8d-deef2c1a1e21.png)

**Comment by 1160914483** [comment]
Are you doing brain segmentation? Can you learn from your profile settings?
