### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by kexul** [NifTK/NiftyNet#119]
when I‘m trying to install niftynet form source code, these things happen:

`Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    if pep440_regex.match(niftynet_version) is None:
TypeError: expected string or bytes-like object`

Any idea? thanks

**Comment by wyli** [comment]
Hi @kexul  could you elaborate how you get this error?

**Comment by kexul** [comment]
@wyli I just downloaded the code, `pip install -r requirements-gpu.txt` , and then I try `python setup.py install`, then the error message appeared. 
enviroments: ubuntu 16.04 , tf 1.7

**Comment by wyli** [comment]
Thanks @kexul for the feedback! The downloaded zip archive doesn't contain versioning information, alternatively you can install the latest version by 
```pip install git+https://github.com/NifTK/NiftyNet.git```.
