### ISSUE TITLE
What the probabilities are saved?

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#121]
Hi, I set the output_prob as 'True' but couldn't find out where they are saved. 

Also, just to make sure that "dropout" is supported right? since the documentation says that if dropout is supported the default value will be 0.5 but it is actually 1. 

Thanks!

**Comment by wyli** [comment]
Thanks @YilinLiu97 the default value is now updated and the probabilities are written to the `save_seg_dir` folder as multi-channel volumes.
