### ISSUE TITLE
Noisy background using isampler regression

### ISSUE THREAD

**Issue by anlarro** [NifTK/NiftyNet#122]
When doing inference after CT-MRI regression using the isampler (niftynet.contrib.regression_weighted_sampler.isample_regression.ISampleRegression), I get noisy backgrounds. This issue does not happen when a use the standard net_regress application. I attach a picture of both cases (isampler left). Training was performed with isampler, but when using net_regress for the final inference I get a smoother output (right).
![noisy](https://user-images.githubusercontent.com/13048251/41286913-5a3ca066-6e41-11e8-8496-9a4c1c243508.PNG)

**Comment by mmodat** [comment]
@wyli @xygorn - Any suggestion as you both contributed to the file that contains this sampler.

**Comment by wyli** [comment]
net_regress implements a more generic version of ISampleRegression, so please use net_regress in this case
