### ISSUE TITLE
CRFAsRNN

### ISSUE THREAD

**Issue by CourantNg** [NifTK/NiftyNet#129]
Hi, I'm using the CRFAsRNNLayer implemented in [https://github.com/NifTK/NiftyNet/blob/dev/niftynet/layer/crf.py](url). I added two lines between Line 190 and Line191 in [https://github.com/NifTK/NiftyNet/blob/dev/niftynet/network/holistic_net.py](url):

`fused_score = merge_layer(soft_scores)`
`crflayer = CRFAsRNNLayer()          # these two lines`
`fused_score = crflayer(input_tensor, fused_score)`
`scores_instances.append(fused_score)`

When I trained a model on Ubuntu, everything was OK. But when I did inference on another Ubuntu with the same model, some wrongs happened: 

`InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [70] rhs shape= [16]`
`[[Node: save/Assign_276 = Assign[T=DT_FLOAT, _class=["loc:@HolisticNet/res_4_0/bn_0/moving_variance"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](HolisticNet/res_4_0/bn_0/HolisticNet/res_4_0/bn_0/moving_variance/biased, save/RestoreV2/_161)]]`
`[[Node: save/RestoreV2/_140 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_146_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:284)]]`

I have no idea about what happened, since everything goes well when I do inference on the original Ubuntu.

Any help is appreciated!

**Comment by wyli** [comment]
Hi @CourantNg I couldn't replicate this issue. By looking at the log it seems that you changed `n_features` to 16 in holistic_net.py when doing inference but trying to load a checkpoint with `n_features` 70?
