### ISSUE TITLE
adding an option for the constant value used in output volume padding

### ISSUE THREAD

**Issue by wyli** [NifTK/NiftyNet#143]
Window aggregators should allow for an adjustable padding constant. 

At the moment the output volumes are padded with zeros (e.g. https://github.com/NifTK/NiftyNet/blob/v0.3.0/niftynet/engine/windows_aggregator_grid.py#L66).

see also https://github.com/NifTK/NiftyNet/issues/141

**Comment by YilinLiu97** [comment]
Hi @wyli , recently I found that although zeros are eliminated by making the volume_padding_size larger than the border, it somehow leads to worse segmentation (significantly lower dice scores). I have done several experiments and think that these are not just coincidences...

**Comment by YilinLiu97** [comment]
Never mind problem solved! As long as in the training process the volume_padding_size is consistently larger than the border, the segmentation performance won't be affected.

**Comment by stian-johnsen** [comment]
A very basic solution to this may be available in the PR https://github.com/NifTK/NiftyNet/pull/337
