### ISSUE TITLE
Error installing editable NiftyNet with pip

### ISSUE THREAD

**Issue by fepegar** [NifTK/NiftyNet#145]
Hi all,

I'm trying a fresh install of NiftyNet. I'm on macOS, using Miniconda. These are my commands:
```shell
conda create -n nntest python -y
source activate nntest
pip install tensorflow==1.7
git clone git@github.com:NifTK/NiftyNet.git
pip install -e NiftyNet
```

And this is what I get:
```python-traceback
Obtaining file:///Users/fernando/git/NiftyNet
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/fernando/git/NiftyNet/setup.py", line 4, in <module>
        from packaging import version
    ModuleNotFoundError: No module named 'packaging'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/fernando/git/NiftyNet/
```

**Comment by fepegar** [comment]
The installation worked after running `pip install packaging`.

**Comment by fepegar** [comment]
I had the same problem on Windows. Had to install manually the following packages before niftynet: `packaging`, `blinker`, `scipy`, `pandas`.

**Comment by dzhoshkun** [comment]
Thanks @fepegar 

The [`packaging` import on line 4](https://github.com/NifTK/NiftyNet/blob/dev/setup.py#L4) seems to be superfluous now, since we are using versioneer for that purpose.
Can you try whether it works after deleting that line?

**Comment by dzhoshkun** [comment]
Re Windows: On Windows [it wasn't possible to install some packages via pip](https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/issues/136), which might have changed in the meantime.
Could the other failing dependencies be due to that problem?

**Comment by fepegar** [comment]
> Can you try whether it works after deleting that line?

I'll try tomorrow.

> Re Windows: On Windows it wasn't possible to install some packages via pip, which might have changed in the meantime.

I installed `scipy` with `pip` on Windows this evening.

> Could the other failing dependencies be due to that problem?

I could install the other three as well.


Note that I get these errors only when I do `pip install -e`.

**Comment by fepegar** [comment]
This is odd. I just tried reproducing and got the same error as in the same comment:
```python-traceback
$ pip install -e git/NiftyNet        ✓  25% (0:41) 🔋  50.02 Dur  23:20:30
Obtaining file:///Users/fernando/git/NiftyNet
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/fernando/git/NiftyNet/setup.py", line 4, in <module>
        from packaging import version
    ModuleNotFoundError: No module named 'packaging'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/fernando/git/NiftyNet/
```

But when I look inside `setup.py`, that line is not present:
```zsh
$ head -n 10 /Users/fernando/git/NiftyNet/setup.py
# -*- coding: utf-8 -*-
import re

from packaging import version
from setuptools import setup, find_packages

import versioneer
from niftynet.utilities.versioning import get_niftynet_version

niftynet_version = get_niftynet_version()
```

**Comment by fepegar** [comment]
After deleting that line, it asks for `nibabel`, then `scipy`, etc. I probably had `nibabel` installed in the environment when I tried on Windows earlier today.

**Comment by dzhoshkun** [comment]
It looks like [editable mode (`-e` flag) attempts to build a wheel](https://pip.pypa.io/en/stable/reference/pip_install/#build-system-interface), which however requires those dependencies (due to [the use of NiftyNet packages in `setup.py`](https://github.com/NifTK/NiftyNet/blob/dev/setup.py#L8).

I think going forward it's quite important to support the editable mode to encourage contributions.

1. A possible solution to the problem is to use the [`setup_requires`](https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires) keyword by duplicating the [`install_requires`](https://github.com/NifTK/NiftyNet/blob/dev/setup.py#L78) dependencies.
2. The `packaging` dependency should now be obsolete, and I suggest we simply remove the respective line.

@fepegar Would you like to give this a try? I'll give you contributor access on the project, so that you can create a branch and work on it.

**Comment by fepegar** [comment]
Thanks @dzhoshkun, I'll se what I can do.

> The packaging import on line 4 seems to be superfluous now, since we are using versioneer for that purpose.
Can you try whether it works after deleting that line?

By the way, package `version` from `packaging` is used [here](https://github.com/NifTK/NiftyNet/blob/dev/setup.py#L15).

**Comment by fepegar** [comment]
Adding the `setup_requires` kwarg doesn't seem to have any effect, I still get the `nibabel` error.

**Comment by dzhoshkun** [comment]
Indeed! Good catch 😃 That means `packaging` should be part of the `setup_requires` set then.

**Comment by dzhoshkun** [comment]
I think the problem is, [a more explicit configuration is required for pip to be able to locate the `setup_requires` dependencies](https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires) (see esp. the linked [distutils configuration files](https://docs.python.org/2/install/index.html#distutils-configuration-files)).

**Comment by fepegar** [comment]
I think you need the config if you want pip to look for the packages somewhere else instead of PyPi, right?

Isn't there another way to specify the NiftyNet version? It seems counterintuitive to me to import the package before installing it anyway. The error comes from trying to run `niftynet.__init__` when importing the function to get the version.

**Comment by dzhoshkun** [comment]
> Isn't there another way to specify the NiftyNet version? It seems counterintuitive to me to import the package before installing it anyway.

I quite agree with you. However this is needed to be able to provide a global versioning scheme that is consistent across different installation types. Any idea on how to decouple the global [version getter](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/utilities/versioning.py#L19) from the setup while still making it available e.g. from within an pip-installed wheel?

**Comment by fepegar** [comment]
In `nibabel`, the version is [read](https://github.com/nipy/nibabel/blob/master/setup.py#L37-L38) from a [file](https://github.com/nipy/nibabel/blob/master/nibabel/info.py#L19-L22) in the repo.

**Comment by fepegar** [comment]
Same for [`nipype`](https://github.com/nipy/nipype/blob/master/nipype/info.py).

**Comment by fepegar** [comment]
In NumPy, the version is explicit in [`setup.py`](https://github.com/numpy/numpy/blob/master/setup.py#L65-L69).

**Comment by fepegar** [comment]
Pillow [reads](https://github.com/python-pillow/Pillow/blob/master/setup.py#L124-L138) the version from a [file](https://github.com/python-pillow/Pillow/blob/master/src/PIL/_version.py).

**Comment by dzhoshkun** [comment]
Thanks @fepegar 

Please see [this merge request](https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/merge_requests/201), since which we use versioneer for automating the version identification based on NiftyNet Git-tags (as opposed to hard-coding it).

As far as I can see, all four libraries have hard-coded version identifiers, unless I'm missing something.

**Comment by fepegar** [comment]
[Matplotlib](https://github.com/matplotlib/matplotlib/blob/38be7aeaaac3691560aeadafe46722dda427ef47/setup.py) uses versioneer as well.

**Comment by dzhoshkun** [comment]
[versioneer does not support retrieving the version of pip-installed packages yet](https://github.com/warner/python-versioneer/issues/180). Hence the need for our custom global version getter (please see [this comment](https://github.com/NifTK/NiftyNet/issues/145#issuecomment-402123382) above), which unfortunately precludes the use of versioneer in the same simple way as in Matplotlib.

**Comment by wyli** [comment]
Ok to install the latest `dev` version, 
now this should work (with cpu-only) :
```
conda create -n nntest python=3.5 
source activate nntest
pip install tensorflow==1.7
pip install -r https://raw.githubusercontent.com/NifTK/NiftyNet/dev/requirements-cpu.txt
pip install git+https://github.com/NifTK/NiftyNet.git
```

with gpu:
```
conda create -n nntest python=3.5 
source activate nntest
pip install tensorflow-gpu==1.7
pip install -r https://raw.githubusercontent.com/NifTK/NiftyNet/dev/requirements-gpu.txt
pip install git+https://github.com/NifTK/NiftyNet.git
```

I'm closing this issue now, please feel free to create new issues to follow up the discussion if needed.
