### ISSUE TITLE
Understanding U-Net shape constraints

### ISSUE THREAD

**Issue by fepegar** [NifTK/NiftyNet#147]
It was hard to me to understand shape constraints when I first tried NiftyNet. I've seen that others have issues as well (#144, #79, #93, #92, #83, #80, #125...), so I wrote a small tutorial:
https://nbviewer.jupyter.org/gist/fepegar/1fb865494cb44ac043c3189ec415d411

Probably DeepMedic and V-Net would be worth explaining as well.

**Comment by tvercaut** [comment]
Thanks, I think we should give this sort of documentation more visibility. This particular gist could be a nice first entry in the FAQ (see #137) that needs to be set up.

**Comment by yshvrdhn** [comment]
@fepegar Is the shape constraints the same for highresnet too ?

**Comment by fepegar** [comment]
@yshvrdhn, the constraints for HigRes3dNet are in the [`network` README](https://github.com/NifTK/NiftyNet/tree/dev/niftynet/network#highres3dnet).

I'm not sure why the image size must be divisible by 8, maybe @wyli can help.

**Comment by yshvrdhn** [comment]
@fepegar thanks! Any idea how I can print the input image size to the network in order to see what is the actual tensor size of the input to the network in nifty net?
