### ISSUE TITLE
3D U-Net toy example

### ISSUE THREAD

**Issue by bilwaj** [NifTK/NiftyNet#15]
Is there a plan to add a toy example with all the other ini files in niftynet/config ?

**Comment by wyli** [comment]
Hi @bilwaj , the config folder was created for demo purposes, as we didn't have detailed documentation for the config options. We're moving those examples (and hopefully trained weights  to the model zoo) https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer/blob/master/model_zoo.md
