### ISSUE TITLE
Inconsistent input and output volume sizes

### ISSUE THREAD

**Issue by fepegar** [NifTK/NiftyNet#153]
I'm running an inference using as input an image **A** with size `(299, 395, 297)`. The inference output is `(299, 396, 297)`.

**A**:
Input voxel size is `(0.46645769476890553, 0.46645772457122797, 0.4664466083049773)`
`pixdim` parameter in config file is `0.5, 0.5, 0.5`
Output voxel size is `(0.4664577245712279, 0.4664577245712279, 0.4664466381072999)`

If I set `pixdim` to `0.466, 0.466, 0.466`, input and output for image **A** have the same size, but image **B** is inconsistent:
**B**
Input size: `(402, 465, 384)`
Output size: `(403, 465, 385)`

**Comment by wyli** [comment]
Right, following your code @fepegar our goal is to have always `size_a == size_a_reconstructed_rounded`, to achive that we need to compensate the quantisation error of the build-in `round` function. My concern is that `round` behaves differently in python2 and 3, we need a bit of extra care when implementing this function.
