### ISSUE TITLE
Spatial window size bug

### ISSUE THREAD

**Issue by ReubenDo** [NifTK/NiftyNet#167]
Hi,
`spatial_window_size = 105` is interpreted as `spatial_window_size = (105,1,1)` instead of `spatial_window_size = (105,105,105)`
Cheers

**Comment by wyli** [comment]
@ReubenDo Just realised this is the intended behaviour so that for 2D cases we could have both `spatial_window_size = (105, 105)` and `spatial_window_size = (105, 105, 1)` as valid options.
