### ISSUE TITLE
ValueError: Unknown keywords in config file: By "keep_prob" did you mean "output_prob"?

### ISSUE THREAD

**Issue by peter850706** [NifTK/NiftyNet#171]
I created my own configuration file with NETWORK parameter 'keep_prob', but I got this error:

ValueError: Unknown keywords in config file: By "keep_prob" did you mean "output_prob"?
 "keep_prob" is not a valid option.

Then I check  this link: http://niftynet.readthedocs.io/en/dev/config_spec.html, and I found the parameter 'keep_prob', can anyone solve this? Thank you!!

(By the way, I also check the source code in: http://niftynet.readthedocs.io/en/dev/_modules/niftynet/utilities/user_parameters_default.html#add_application_args, 'keep_prob' is in there.)

**Comment by Zach-ER** [comment]
Hi there, 
I think that the most likely explanation is that you don't have the latest version of niftynet: this feature was added recently. Try pulling the latest version and seeing if this problem persists?

**Comment by peter850706** [comment]
Hi, I install the latest version of niftynet via pip, but I still got the same error. My server's OS is Ubuntu 17.10 (GNU/Linux 4.13.0-43-generic x86_64), and I build the environment via conda. Here are the error messages:

```
CRITICAL:tensorflow:Optional Python module cv2 not found, please install cv2 and retry if the application fails.
WARNING:niftynet: From ~/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
NiftyNet version 0.3.0
INFO:niftynet: Import [BRATSApp] from ~/niftynet/extensions/VIPCUP/wtnet/brats_seg_app.py.
Traceback (most recent call last):
  File "~/anaconda3/envs/test/bin/net_run", line 11, in <module>
    sys.exit(main())
  File "~/anaconda3/envs/test/lib/python3.6/site-packages/niftynet/__init__.py", line 64, in main
    system_param, input_data_param = user_parameters_parser.run()
  File "~/anaconda3/envs/test/lib/python3.6/site-packages/niftynet/utilities/user_parameters_parser.py", line 151, in run
    _check_config_file_keywords(config)
  File "~/anaconda3/envs/test/lib/python3.6/site-packages/niftynet/utilities/user_parameters_parser.py", line 276, in _check_config_file_keywords
    _raises_bad_keys(config_keywords, error_info='config file')
  File "~/anaconda3/envs/test/lib/python3.6/site-packages/niftynet/utilities/user_parameters_parser.py", line 311, in _raises_bad_keys
    key, closest, EPILOG_STRING, error_info))
ValueError: Unknown keywords in config file: By "keep_prob" did you mean "output_prob"?
 "keep_prob" is not a valid option.

======
For more information please visit:
http://niftynet.readthedocs.io/en/dev/config_spec.html
======

```

**Comment by fepegar** [comment]
@wyli When I try that command in a new `conda` environment I get errors asking for `packaging`, `nibabel`, etc. See #145

**Comment by wyli** [comment]
Thanks @peter850706 for tracking this down!

**Comment by peter850706** [comment]
@wyli @Zach-ER @fepegar Thanks all of you for the replies!
