### ISSUE TITLE
Move CI tests to GIFT-Little

### ISSUE THREAD

**Issue by dzhoshkun** [NifTK/NiftyNet#173]
As discussed with @tvercaut and @wyli we are going to move the current CI tests from Adelie to the new CI server GIFT-Little. This issue is for testing that transition.

**Comment by dzhoshkun** [comment]
* [ ] persistently set GPU for quick and slow tests, to ensure they run on separate GPUs?

**Comment by wyli** [comment]
Hi Dzhosh,

This looks strange, may I have ssh access to Little? I can have a look tomorrow.
(I've seen some different error messages for the same line of command
`net_autoencoder`.
Couldn't locate the issue precisely, but retrying the CI tests often
runs without an error.)

Thanks,
Wenqi
On Tue, 31 Jul 2018 at 10:17, Dzhoshkun Ismail Shakir
<notifications@github.com> wrote:
>
> @wyli Is this segfault expected? Does it ever happen on Adelie? (This particular segfault occurred on Little)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Research Associate
Dept of Biomedical Engineering
King's College London

**Comment by dzhoshkun** [comment]
I've retried the failing build. This time [`net_segment` segfaults](https://gitlab.com/NifTK/NiftyNet/-/jobs/85607549). Will retry again.

**Comment by dzhoshkun** [comment]
* [ ] revert irrelevant changes to CI script

**Comment by dzhoshkun** [comment]
@wyli This time the `pip-installer` script seems to fail... It's either a [segfault](https://gitlab.com/NifTK/NiftyNet/-/jobs/85665553) or an [unknown node](https://gitlab.com/NifTK/NiftyNet/-/jobs/85648421). It'd be great if you could have a look. I'll continue retrying in the meantime.

**Comment by dzhoshkun** [comment]
Everything seems to run well up to the [`pip-camera-ready` script, which should (and does) fail for all commits not tagged with a `v` prefix](https://gitlab.com/NifTK/NiftyNet/-/jobs/85584462).

The `release-notes` script (which follows the `pip-camera-ready` script) is minimal, and also does a `chandler push` for the release notes. So no testing action item for it at this stage. Worst case we can re-run it. However maybe:

* [ ] set up chandler on Little

**Comment by dzhoshkun** [comment]
* [ ] cross-check NVIDIA driver (against the Adelie) for the segfault issues

**Comment by dzhoshkun** [comment]
I've found [this discussion](https://github.com/tensorflow/tensorflow/issues/19347#issuecomment-390064429), which talks about [uncorrectable ECC](https://stackoverflow.com/a/11839929) leading to segfaults.

I've tried to reproduce the segfault by running:

```bash
for i in `seq 1 10`; do python net_gan.py inference -c $niftynet_dir/config/GAN_demo_train_config.ini; done
```

inspired by [this failed build](https://gitlab.com/NifTK/NiftyNet/-/jobs/85652742), keeping an eye on the output of the `nvidia-smi` output. However I couldn't reproduce the segfault.

**Comment by dzhoshkun** [comment]
The [NVIDIA driver 384.130](https://www.google.com/search?ei=LqphW9WmAYzTwALjvoO4Cg&q=384.130+segfault&oq=384.130+segfault&gs_l=psy-ab.3...2724.6530.0.7025.9.9.0.0.0.0.248.660.8j0j1.9.0....0...1c.1.64.psy-ab..0.0.0....0.UUB0n5vOmGM) (Little) seems to have similar Google hits as [384.111](https://www.google.com/search?q=384.111+segfault&oq=384.111+segfault&aqs=chrome..69i57.1981j0j7&sourceid=chrome&ie=UTF-8).

**Comment by dzhoshkun** [comment]
@wyli Nope. I haven't set any memory limits on Little yet.

**Comment by dzhoshkun** [comment]
It's interesting that in the last segfaulting CI task we get:

```
/home/gitlab-runner/builds/bf2aef4f/0/NifTK/NiftyNet/niftynet-dev-test-py3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/gitlab-runner/builds/bf2aef4f/0/NifTK/NiftyNet/niftynet-dev-test-py3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
```

Which I fixed yesterday by [downgrading NumPy to 1.14](https://github.com/gift-surg/docs/wiki/GIFT-Little#known-issues). But apparently some settings are different on the `gitlab-runner` account. Will take a look.

**Comment by dzhoshkun** [comment]
[First pass succeeded](https://gitlab.com/NifTK/NiftyNet/-/jobs/86579063), but [second pass segfaulted](https://gitlab.com/NifTK/NiftyNet/-/jobs/86593913).

**Comment by dzhoshkun** [comment]
It's been reported that [import order might be the cause of segfaults](https://github.com/tensorflow/tensorflow/issues/2034#issuecomment-212697197).

**Comment by wyli** [comment]
[a conflict installing scikit-learn after tensorflow?]](https://stackoverflow.com/questions/45134309/sporadic-core-dumps-segmentation-faults-illegal-instruction-using-tensorflow)

I couldn't replicate the issue by running the ci script manually with or without virtualenv.

**Comment by wyli** [comment]
I think the segfault has gone after upgrading to TF1.9 and resetting the session/graph https://github.com/NifTK/NiftyNet/blob/403589122ca5c233348100a6d2f1f51737b4c6b0/niftynet/__init__.py#L143-L149

**Comment by dzhoshkun** [comment]
Great! I've now upgraded the global TF installation on Little to 1.9 as well.
