### ISSUE TITLE
Clarify license of models / model+weights coming from net_download

### ISSUE THREAD

**Issue by tvercaut** [NifTK/NiftyNet#180]
Since net_download fetches files from external urls, the licence of these external files is currently unclear (even if we fix https://github.com/NifTK/NiftyNetModelZoo/issues/1), see e.g.:
https://www.dropbox.com/s/cnbsszxa418xc1x/anisotropic_nets_brats_challenge_weights.tar.gz

which is referred to from 
https://github.com/NifTK/NiftyNetModelZoo/blob/master/anisotropic_nets_brats_challenge_model_zoo.ini

My suggestion would be to ask contributors to add a licence file in each of the external compressed files and recommend to use a [cc-by](
https://creativecommons.org/licenses/by/4.0/) or [cc0](https://creativecommons.org/share-your-work/public-domain/cc0/) license.

Checking that a licence file is present could be a prerequisite to merge a new model in (at least at the time of submission).

**Comment by wyli** [comment]
cc-by license included in each of the model zoo entry's readme
