### ISSUE TITLE
About data augmentation

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#187]
Hi,
I'm wondering, does the augmentation increase the number of samples or just do random deformation on existing samples and the total sample size remains the same?  I know that augmentation implies increase in sample size but from what I read in "image_reader.py", it doesn't seem that 's how it works.  Also, is it possible to know roughly how much data we can get after augmentation?  Thanks so much!

**Comment by wyli** [comment]
Hi @YilinLiu97  the augmentation layers will be applied on the existing samples, total training elements will still be batch_size x number of iterations x num_gpus. There is a demo here: https://github.com/NifTK/NiftyNet/blob/dev/demos/unet/U-Net_Demo.ipynb
