### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by yyydido** [NifTK/NiftyNet#19]
Are there any examples for ToyNet? or in other words,are there any examples for how to developing a new network from data prepare to train ?

**Comment by wyli** [comment]
Hi @yyydido for developing new networks, the guide is available here: http://niftynet.readthedocs.io/en/dev/extending_net.html#make-the-module-loadable
In terms of training data preparation, converting them into NIfTI format (https://nifti.nimh.nih.gov/) is preferred. Then you could specify the files to load in a configuration file (http://niftynet.readthedocs.io/en/dev/config_spec.html#input-data-source-section)
