### ISSUE TITLE
Tables are broken in config docs

### ISSUE THREAD

**Issue by fepegar** [NifTK/NiftyNet#193]
For some of the reason, some but not all of the tables that were fixed in #146 are not rendered properly in the config spec website, e.g. https://niftynet.readthedocs.io/en/dev/config_spec.html#input-data-source-section

**Comment by fepegar** [comment]
Maybe we should report an issue in the [`sphinx-markdown-tables` repo](https://github.com/ryanfox/sphinx-markdown-tables) with that you link you posted. The maintainer might have an idea of what could be happening.

**Comment by fepegar** [comment]
Do you have an idea of why only some of the tables stopped working?

**Comment by fepegar** [comment]
Thanks @ryanfox!

**Comment by wyli** [comment]
Thanks @ryanfox! Still it gives the chicken and egg problem http://readthedocs.org/projects/niftynet/builds/7627523/
with this [`requirements.txt`](https://github.com/NifTK/NiftyNet/blob/dev/doc/requirements.txt).

Perhaps making [the version number hard-code](https://github.com/ryanfox/sphinx-markdown-tables/blob/v0.0.3/setup.py#L12) is not a bad idea?

**Comment by ryanfox** [comment]
I wanted to avoid hard-coding it because then there would be two places to update and keep in sync. At any rate, the circular import should be resolved for both python 2 and 3 in v0.0.9 (latest on pypi as of now).

**Comment by wyli** [comment]
Now the tables look great, thanks @ryanfox and @fepegar!
