### ISSUE TITLE
Update the NiftyNet website

### ISSUE THREAD

**Issue by tvercaut** [NifTK/NiftyNet#213]
The website still refers to cmiclab as being the main repo: http://niftynet.io

This needs to be addressed. At the same time, we should transfer the [website repo currently on cmiclab](https://cmiclab.cs.ucl.ac.uk/CMIC/niftynet-website) to GitHub.

@mjorgecardoso do you have the rights to update the website?

**Comment by wyli** [comment]
website source code is now at https://github.com/NifTK/NiftyNet_Website
