### ISSUE TITLE
Additional u-net demo with histology dataset

### ISSUE THREAD

**Issue by wyli** [NifTK/NiftyNet#244]
Because 
- At the moment the u-net demo uses a dataset that requires signing up to download;
- There's no worked example for histology image analysis.

It would be good to run the u-net demo on histology data such as Sirinukunwattana et al., https://warwick.ac.uk/fac/sci/dcs/research/tia/glascontest/download/ 
there's a URL to download the data immediately.

**Comment by tvercaut** [comment]
@stian-johnsen this might be a good issue to start with to get your feet wet with NiftyNet

**Comment by stian-johnsen** [comment]
This was done and merged here: https://github.com/NifTK/NiftyNet/commit/902ca44ffb2e4f059bded511d0b2ddd26ed862d9
