### ISSUE TITLE
binarizer only applied to inferred image not groundtruth

### ISSUE THREAD

**Issue by sia79** [NifTK/NiftyNet#245]
When using the evaluation functionality I get wrong dice values for my labels. Debugging the code I found that the binarizer is not working as I expected and in fact all computations are based on calculations using a binarized inferred image and the **original** ground truth image (which has many values).

Changing the binarizer to:

```python
def binarizer(data):
        """
        This function binarizes a segmentation based on a specified
        label (defined by outer function)
        :param data: a data dictionary as built by ImageReader
        :return: a numpy array representing a binary label map
        """
        if output_prob:
            out = np.argmax(data['inferred'], -1)
        else:
            out = data['inferred']
        return out == label, data['label'] == label
```
(`data['label'] == label` is currently to just return `data['label']`)

fixes the issue, however the real issue might be something else.

**Comment by MancaZerovnikMekuc** [comment]
A mention of this in documentation would be quick for you and necessary for the community. Evaluation is returning false values not just for Dice coefficient but for every multi-modal metric which use conf. matrix. Can cause a lot of problems to a user.
