### ISSUE TITLE
NotImplementedError failed to generate sampling locations

### ISSUE THREAD

**Issue by MatthewTwente** [NifTK/NiftyNet#25]
Dear NiftyNet team,

I am currently running a pip installed NiftyNet with Tensorflow 1.4 on Ubuntu 16.04 with a Nvidia Tesla P100 12 gb GPU. If more information is required please let me know. I am new to deep learning and trying to train four different architectures (DeepMedic, HighRes3dNet, UNet and VNet) on 1 data set. I keep the hyperparameters of these architectures the same as in the config files. Everytime I run a network, I get the following error message:

CRITICAL:niftynet: Don't know how to generate sampling locations: Spatial dimensions of the grouped input sources are not consistent. {(431, 433, 531), (611, 613, 967)}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/image_window_buffer.py", line 143, in _push
    for output_dict in self():
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/sampler_uniform.py", line 83, in layer_op
    self.window.n_samples)
  File "/usr/local/lib/python3.5/dist-packages/niftynet/engine/sampler_uniform.py", line 151, in rand_spatial_coordinates
    raise NotImplementedError
NotImplementedError

The dimensions after the first error line are different for every training run and for every network. I use the should_stop function using -a "niftynet.application.set_iteration_update()". This error message usually ends up after a certain amount of iterations, around 150 to 250 iterations depening on the network used. I checked all the datafiles for an inconsistent file but there wasnt any. All the images have an image spacing of [1,1,1]. The spatial window size is the same as the config file of the network provides. I checked the sizes of the volumes with their respective labels and they are all the same as well. The results after this error message are saved: I get logs, tfevents, models and a setting_train.txt.

I am unsure how to go about this error message. Any help is much appreciated.

**Comment by MatthewTwente** [comment]
I have also tried using a resize sampler, but this works horribly slow. There must be a better way to fix this sampling method. If necessary I can add my config file as well.

**Comment by wyli** [comment]
Hi @MatthewTwente for the first issue reported, I reckon it's a data file dimension issue. Otherwise, could you please send me some data for replicating the problem?

**Comment by wyli** [comment]
For the resize sampler, it's calling "scipy.ndimage.zoom" https://github.com/NifTK/NiftyNet/blob/dev/niftynet/engine/sampler_resize.py#L120 this could be slow if there isn't enough memory.

**Comment by MatthewTwente** [comment]
Thank you for answering. Unfortunately, I can not share my data. I have decided to check my data for inconsistencies and will update this issue if I find the reason for the problems or solution. 

I have a small additional question. Did I set the early stopping function correctly? Currently I use: -a "niftynet.application.set_iteration_update()" after run_segment. Does this work or should I add a boolean value such as set_iteration_update(true)?

**Comment by wyli** [comment]
Hi @MatthewTwente Thanks for the update, the `-a` command will be ignored in this case. To customise the behaviour, a new application needs to be created to overwrite `set_iteration_update()`, an example in available here: https://github.com/NifTK/NiftyNet/blob/dev/niftynet/contrib/learning_rate_schedule/decay_lr_application.py#L75
