### ISSUE TITLE
Add some comments about DenseVNet

### ISSUE THREAD

**Issue by EdwardMa12593** [NifTK/NiftyNet#26]
Dear NiftyNet team,
NiftyNet is really an excellent work. Thank you very much.
When I read the [dense_vnet.py](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/network/dense_vnet.py), I couldn't understand the network architecture very well. For instance, where are the upsampling blocks?
Would it be possible for you to add some comments to dense_vnet.py.

By the way, when the preprint of "Automatic multi-organ segmentation on abdominal CT with dense V-networks" can be available?

Looking forward to your reply!
Best,
Edward.

**Comment by wyli** [comment]
Hi @EdwardMa12593 The paper is under revision, we'll finalise the code soon and will keep you updated.

**Comment by EdwardMa12593** [comment]
Thank you. I'm very excited about it.

**Comment by wyli** [comment]
Doc&style are now improved:
https://github.com/NifTK/NiftyNet/blob/b9cd620563d67cbee528ff67a3d87372a1e09cd7/niftynet/network/dense_vnet.py

**Comment by wyli** [comment]
Paper is available online:
https://doi.org/10.1109/TMI.2018.2806309
