### ISSUE TITLE
Performing 3D segmentation with NiftyNet

### ISSUE THREAD

**Issue by abderhasan** [NifTK/NiftyNet#263]
Hello,

I'm just starting with NiftyNet and trying to perform 3D segmentation. I couldn't find some guide for started to perform such task. Any guides or tutorials you can kindly refer me to?

Thanks a lot.

**Comment by JunMa11** [comment]
Hi, there are some [demos](https://github.com/NifTK/NiftyNet/tree/dev/demos) here.
