### ISSUE TITLE
Individual Dice Scores

### ISSUE THREAD

**Issue by Farihaa** [NifTK/NiftyNet#276]
I am using dense vnet architecture for multi-organ segmentation of abdominal cavity using "Beyond the Cranial Vault" dataset.
The developers of dense vnet print individual dice scores of the organs on terminal while overall dice loss is added to tensorboard in "dice-hinge.py" file.
I want to add individual dice scores to tensorboard as well to analyze the trend for individual organs. I have not been able to do that.

**Comment by Zach-ER** [comment]
Hi there, 
if you can find the print statement that yields the individual dice scores, you should be able to add them to tensorboard with something like: 

```
            outputs_collector.add_to_collection(
                var=dice_organ_1, name='dice_organ_1,
                average_over_devices=True, summary_type='scalar',
                collection=TF_SUMMARIES)
```

Does this help?

**Comment by chengjianhong** [comment]
> Hi there,
> if you can find the print statement that yields the individual dice scores, you should be able to add them to tensorboard with something like:
> 
> ```
>             outputs_collector.add_to_collection(
>                 var=dice_organ_1, name='dice_organ_1,
>                 average_over_devices=True, summary_type='scalar',
>                 collection=TF_SUMMARIES)
> ```
> Does this help?

Dear Zach-ER,
I also need to print the Dice Scores When I use the ScaleNet architecture  for segmenting brain tumor. and I find the print statement as your above said. But I don't know  how to compute the dice score at here?

**Comment by Farihaa** [comment]
So I solved this issue for myself a few months ago. I saved the terminal- log files and parsed dice scores from them. Then I saved these parsed files as excel files and made any kind of graph that I wanted to make. I could not make individual dice score graphs within niftynet framework.
