### ISSUE TITLE
Contradiction:3D U-Net Dimension size:should it be 92+8*M or should it be divisible by 8?

### ISSUE THREAD

**Issue by qianjiangcn** [NifTK/NiftyNet#277]
According to the Q&A part, the input spatial window size of 3D Unet should be 92+8*M (M>=0)
link (https://gist.github.com/fepegar/1fb865494cb44ac043c3189ec415d411)

But when I try to run the network, it reports error:
```python-traceback
ValueError: input tensor's spatial dimensionality not not compatible, please tune the input window sizes:
        assert layer_util.check_spatial_dims(images, lambda x: x % 8 == 0)
```

Does this mean that the windows size should be divisible by 8?
But 92 is apparently indivisible by 8.

So what spatial window size should I set for 3D Unet exactly?
Thank you very much!

**Comment by JunMa11** [comment]
Comment the following two lines in `./network/unet.py 121-122`  would work for your case.
```python    
 crop_layer = CropLayer(border=44, name='crop-88')
 output_tensor = crop_layer(output_tensor)
```

**Comment by fepegar** [comment]
Hi @qianjiangcn 

The constraints in my tutorial are general, about the original implementation of U-Net. I have added a cell about NiftyNet's implementation.
