### ISSUE TITLE
how to print out dropout rate during training?

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#283]
Hi, I guess that I may need to modify the application.variables.py, but I'm not exactly sure how to do it. Any help is appreciated!

**Comment by fbragman** [comment]
The dropout rate is defined the layer_op of ConvolutionalLayer (https://github.com/NifTK/NiftyNet/blob/a0eab6ea24b45cfe1effd0d6a7b51461beb6946c/niftynet/layer/convolution.py#L168). It is defaulted to None.

You can modify it when you call the ConvolutionalLayer in the network file e.g.

        conv_layer = ConvolutionalLayer(...)
        output = first_conv_layer(input, is_training, keep_prob=)

**Comment by YilinLiu97** [comment]
Thank you for the help! @fbragman  and sorry I didn't make my question clear but I've solved the problem now. Thanks!
