### ISSUE TITLE
where in the codes that patches are stitched?

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#288]
Hi, I'm wondering where can I find the codes for reconstructing the volume from patches? Thanks.

**Comment by jchen42703** [comment]
Hi,
The code for reconstructing patches is located in [ `/niftynet/engine`](https://github.com/NifTK/NiftyNet/tree/dev/niftynet/engine). They are the `windows_aggregator_`'s .
i.e. [`windows_aggregator_base.py`](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/engine/windows_aggregator_base.py)

From,
Joseph
