### ISSUE TITLE
how to set spatial_window_size properly?

### ISSUE THREAD

**Issue by EdwardMa12593** [NifTK/NiftyNet#29]
Dear niftynet developer,
I'm confused about setting the [`spatial_window_size`](https://github.com/NifTK/NiftyNet/tree/dev/config#spatial_window_size) parameter in the `network`. 

For instance, I have 100 volumes which are varying in the number of slices. To be precise, the dimension of the first volume is `512*512*125`, the second volume's dimension is `512*512*203`, and so on. 
If I set the `spatial_window_size` as `64*64*3`, how many inputs would be generated?
Because `64*64*3` can't be divided by both `512*512*125` and ` 512*512*203`. And I also don't know where I can set the step size of the sliding window.
Would it be possible for you to give me some advice on how to set the `spatial_window_size` parameter for `densevnet`?

By the way, are there some constraints about [`densevnet`](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/network/dense_vnet.py) like [other networks](https://github.com/NifTK/NiftyNet/tree/dev/niftynet/network) in `Network model references`?

Looking forward to your reply.
Best wishes!

Edward

**Comment by wyli** [comment]
Hi @EdwardMa12593 

Functions for generating image windows according to `spatial_window_size` are defined in the files named `niftynet/engine/sampler_*.py`. Specifically for the grid sampler (sliding window), 
 sampling coordinates of the windows are defined [here](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/engine/sampler_grid.py#L116). It first computes all sampling points along each dimension and creates a sampling grid with `np.meshgrid`.

For `densevnet`, by default the only spatial constraint I can see is that all input spatial dimensions should be divisible by 8: https://github.com/NifTK/NiftyNet/blob/dev/niftynet/network/dense_vnet.py#L189 @eligibson might have more comments on this.
