### ISSUE TITLE
How to create new network

### ISSUE THREAD

**Issue by chengjianhong** [NifTK/NiftyNet#292]
Hello, I want to create new network and I also see the documentation that allows users create new network. But I don't know how to associate the **network name** in config file and my **customized network** ?

**Comment by C-nit** [comment]
In the [documentation](https://niftynet.readthedocs.io/en/dev/extending_net.html#call-newnet-from-application) it's shown how to make NiftyNet find your new network and the example shows how to use it on the command line:
`--name my_network_collection.new_net.NewNet`

I guess you didn't find the paragraph [overriding-the-arguments](https://niftynet.readthedocs.io/en/dev/config_spec.html#overriding-the-arguments). In the config.ini, simply put  
 ```ini
[NETWORK]
name = my_network_collection.new_net.NewNet
```

**Comment by chengjianhong** [comment]
Yes, I Know. Thank you very much!
