### ISSUE TITLE
Inference Segmentation to 1, sampling problem?

### ISSUE THREAD

**Issue by HansLeonardVanBrueggemann** [NifTK/NiftyNet#30]
Dear all, 

while training a VNet I see that the Dice loss is stuck at 0.5 and the resulting segmentation from the inference is label 1 everywhere. 

I suppose it has to do with the uniform sampling: given that the labels are quite sparse most of the sampling result in chunk of the original image with only one label. 

Is there a way to keep the label distribution in consideration while sampling?

**Comment by wyli** [comment]
Hi @HansLeonardVanBrueggemann I think 'how to keep the label distribution while sampling' is often data/application-dependent, it's difficult to define general rules and robust implementations.... as a starting point, we have a selective sampler implemented in [`niftynet/contrib/segmentation_selective_sampler`](https://github.com/NifTK/NiftyNet/tree/v0.2.1/niftynet/contrib/segmentation_selective_sampler) for image segmentation. It selects image windows based on predefined criteria - e.g. a minimum number of unique labels present in a window.  Another example is window selection based on predefined weight map [`niftynet/engine/sampler_weighted.py`](https://github.com/NifTK/NiftyNet/blob/v0.2.1/niftynet/engine/sampler_weighted.py) currently used in the [regression application](https://github.com/NifTK/NiftyNet/blob/v0.2.1/niftynet/application/regression_application.py#L48).
