### ISSUE TITLE
Cuda 9.0 requirement

### ISSUE THREAD

**Issue by kmouts** [NifTK/NiftyNet#308]
Hello, 

I try to install NiftyNet on Windows 10 64bit and Anaconda. 
With the command: 

> net_download dense_vnet_abdominal_ct_model_zoo

I get:

> ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive

However, I have installed CUDA 10. Is it possible to continue with the newer CUDA?

**Comment by ericspod** [comment]
This is an issue with your Python install. Niftynet and the zoo are all pure Python essentially, nothing is compiled. It is your version of Tensorflow which expects CUDA 9.0, depending on where you got it from (conda or pip) you should be able to get a version for CUDA 10.0 or you'll have to install version 9.0.
