### ISSUE TITLE
Add option to perform isotropic scaling

### ISSUE THREAD

**Issue by fepegar** [NifTK/NiftyNet#322]
I think it would be useful to add an option so that the same random scaling is applied to all dimensions. I can work on it.

**Comment by Zach-ER** [comment]
Maybe I don't understand, but isn't this what the `zoom` preprocessing option does?

**Comment by fepegar** [comment]
I forgot to mention this issue in the corresponding PR: https://github.com/NifTK/NiftyNet/pull/324

What's the `zoom` preprocessing option? Can you point me to some code/docs?

**Comment by fepegar** [comment]
@Zach-ER, in the previous implementation, different scaling percentages were computed for different dimensions. This could make a prostate look like a sausage and would probably be undesired. The new flag is to make sure that a similarity transform is applied to the volume, with a single scaling factor for all axes.
