### ISSUE TITLE
Bug on Rotation augmentation

### ISSUE THREAD

**Issue by JunMa11** [NifTK/NiftyNet#329]
Thanks for the excellent project. It helped me a lot for my research.

I'd like to augment the training data off-line following the [ImageReader example](https://github.com/NifTK/NiftyNet/blob/dev/demos/module_examples/ImageReader.ipynb).

However, the augmentation results are degenerated.
Following is the code that I used.

```python
#%% augument dataset by rotation
from niftynet.layer.rand_rotation import RandomRotationLayer as Rotate
from niftynet.io.image_reader import ImageReader
import nibabel as nb
import numpy as np
import sys

niftyent_path = './'
sys.path.insert(0, niftyent_path)


def RotateAug(rotate_angle):
    data_param = {'MR': {'path_to_search': './data/BraTS18', 'filename_contains': 'brain-ori-flair-', 
                         'filename_not_contains': 'ro'},
    'label': {'path_to_search': './data/BraTS18', 'filename_contains': 'brain-tumor-label-'}}
    reader = ImageReader().initialise(data_param)
    rotation_layer = Rotate()
    rotation_layer.init_uniform_angle(rotate_angle)
    reader.add_preprocessing_layers([rotation_layer])
    
    return reader

for rotate in range(-1, 0):
    rotate_angle = np.float32([rotate, rotate+1])

    reader = RotateAug(rotate_angle)
    idx = 0
    _, aug_img, _ = reader(idx)
    img_name = reader.get_subject(idx)['MR']
    img_nii = nb.load(img_name)
    label_name = reader.get_subject(idx)['label']
    label_nii = nb.load(label_name)
    
    img_save_name = img_name.split('.nii.gz')[0] + 'ro' + str(rotate) + '.nii.gz'
    img_save_nii = nb.Nifti1Image(np.squeeze(aug_img['MR']), img_nii.affine, img_nii.header)
    nb.save(img_save_nii, img_save_name)

    label_save_name = label_name.split('.nii.gz')[0] + 'ro' + str(rotate) + '.nii.gz'
    label_save_nii = nb.Nifti1Image(np.squeeze(aug_img['label']), label_nii.affine, label_nii.header)
    nb.save(label_save_nii, label_save_name)    
```

Augmentation results have two main errors.
1) The image is missed partially.
2) The label has some errors especially on boundaries.

The bigger the rotation degree, the worse the results.
Following picture shows an example. The left image is original. The middle and right images are augumentation results with rotation angle `-1` and `-10`, respectively.
![Markdown](http://i2.bvimg.com/595387/5d44efe33f62647d.png)

Would it be possible for you to tell me how to solve this problem?

Looking forward to your reply.
Best regards,
Edward

**Comment by wyli** [comment]
Hi @EdwardMa12593 glad to know that. For your first issue, what would be the expected results in your mind? for the second, I think the label's interpolation order should be zero, could you confirm that?

**Comment by JunMa11** [comment]
Dear @wyli ,
I'm so sorry for the late reply.

I do the rotation augmentation for Brats18 data by `niftynet`. 
Following your guidance,  I set the label's interpolation order as `0`, but **one label value missed in the label augmentation result**. 

I also test another data augmentation tool [batchgenerators](https://github.com/MIC-DKFZ/batchgenerators), the image augmentation result is similar to niftynet, but the label augmentation results are different. 

![Aug. Results](http://i1.bvimg.com/595387/02131a4040d722ec.png)

One difference is that niftynet uses [scipy.ndimage.affine_transform](https://github.com/NifTK/NiftyNet/blob/0429b0429088ea274d474bbb885bb4b53cbe6185/niftynet/layer/rand_rotation.py#L100), while batchgenerators use [scipy.ndimage.map_coordinates](https://github.com/MIC-DKFZ/batchgenerators/blob/0c46a1b8293bab0b79c03be4d5abfa28f83875af/batchgenerators/augmentations/utils.py#L126).

But I do not figure out the key reason for the label issue in niftynet rotation results.

Following is my code for niftynet rotation augmentation.
```python
from niftynet.layer.rand_rotation import RandomRotationLayer as Rotate
from niftynet.io.image_reader import ImageReader
import nibabel as nb
import numpy as np
import sys

niftyent_path = './'
sys.path.insert(0, niftyent_path)


def RotateAug(rotate_angle):
    data_param = {'MR': {'path_to_search': r'E:\Data\DataAug\brats2018', 'filename_contains': 'flair-', 
                         'filename_not_contains': 'ro', 'interp_order': 3},
    'label': {'path_to_search': r'E:\Data\DataAug\brats2018', 'filename_contains': 'label-', 'interp_order': 0}}
    reader = ImageReader().initialise(data_param)
    rotation_layer = Rotate()
    rotation_layer.init_uniform_angle(rotate_angle)
    reader.add_preprocessing_layers([rotation_layer])
    
    return reader
#%%
for rotate in range(-10, -9):
    rotate_angle = np.float32([rotate, rotate+1])

    reader = RotateAug(rotate_angle)
    idx = 0
    _, aug_img, _ = reader(idx) # argument results
    
    
    # obtain original image header info and save rotated image    
    img_name = reader.get_subject(idx)['MR']
    img_nii = nb.load(img_name)
    label_name = reader.get_subject(idx)['label']
    label_nii = nb.load(label_name)
    # save results
    img_save_name = img_name.split('.nii.gz')[0] + '-ro' + str(rotate) + '.nii.gz'
    img_save_nii = nb.Nifti1Image(np.squeeze(aug_img['MR']), img_nii.affine, img_nii.header)
    nb.save(img_save_nii, img_save_name)

    label_save_name = label_name.split('.nii.gz')[0] + '-ro' + str(rotate) + '.nii.gz'
    label_save_nii = nb.Nifti1Image(np.squeeze(aug_img['label']), label_nii.affine, label_nii.header)
    nb.save(label_save_nii, label_save_name)    


```

**Comment by wyli** [comment]
Your augmentation code looks ok, so what's your expected output? 
could check your `aug_img['label']` before saving:
```python
uniq_vals, uniq_counts = np.unique(aug_img['label'], return_counts=True)
print(uniq_vals, uniq_counts)
```

**Comment by JunMa11** [comment]
Hi @wyli ,

I'm very appreciated with your help. 
The orginal label is 4 classes, so my expeted label output should also have 4 classes, but I only find 3 classes when opening label by itk-snap.

**Following your guidance, I find the cause of the label error.**

> print(uniq_vals, uniq_counts) ->[0. 1. 2. 4.] [8827057   11008   63737   26198]

The code is ok, the reason for my previous label error is the `dtype` of aug_img['label']. `aug_img['label'].dtype` is `float32`, I need to convert it to `uint8` before `nb.save`.

Thank you very much for your time and help.
