### ISSUE TITLE
Dynamic Window Size

### ISSUE THREAD

**Issue by HansLeonardVanBrueggemann** [NifTK/NiftyNet#33]
Dear All, 

I'm trying to use dynamic window size for segmentation, which should be at -1. 
But I can't understand why sometimes it's working and sometimes it's not. 

When it doesn't work, I get the following message 
`TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'`

What's the requirement for dynamic sizing?

**Comment by wyli** [comment]
Hi @HansLeonardVanBrueggemann the dynamic window size feature is only experimental at the moment -- `sampler_*`, `loss_segmentation` (AFAIR) support this; but many components in `niftynet/network` requires specified fixed size.
