### ISSUE TITLE
Restore frozen layers

### ISSUE THREAD

**Issue by skaliy** [NifTK/NiftyNet#335]
I am trying to restore frozen layers, as explained in the transfer_learning.md, but I'm getting 
`ValueError: No variables to optimize`.  
Any solutions for this? 

Here is a snippet of my current config file: 

**[NETWORK]**
window_sampling = weighted

name = highres3dnet
activation_function = leakyrelu
batch_size = 1
decay = 0.0
reg_type = L2
queue_length = 36
normalisation = False
whitening = True 
foreground_type = threshold_plus

**[TRAINING]**
vars_to_restore = ^((?!(Adam)).)*$

lr = 0.0001
loss_type = Dice
starting_iter = 5558

**Comment by wyli** [comment]
Hi @skaliy probably you need to set a `vars_to_freeze` in `[TRAINING]` as well, by default `vars_to_freeze` uses the value of `vars_to_restore` (i.e. restored variables will not change during training).
https://niftynet.readthedocs.io/en/dev/transfer_learning.html#freezing-model-weights
