### ISSUE TITLE
Undefined name 'field_interpretation' in spatial_transformer.py

### ISSUE THREAD

**Issue by cclauss** [NifTK/NiftyNet#35]
https://github.com/NifTK/NiftyNet/blob/dev/niftynet/layer/spatial_transformer.py#L122

flake8 testing of https://github.com/NifTK/NiftyNet

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./niftynet/layer/spatial_transformer.py:122:65: F821 undefined name 'field_interpretation'
                                           field_interpretation=field_interpretation,
                                                                ^
1     F821 undefined name 'field_interpretation'
```

**Comment by wyli** [comment]
Many thanks for the feedback! It's now rectified.
