### ISSUE TITLE
explanation of the`load_image` function and the dataflow

### ISSUE THREAD

**Issue by wyli** [NifTK/NiftyNet#36]
#31 and #34 asked for clarifications of [`load_image(filename)`](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/io/misc_io.py):
> how the image data is transferred to the network?
> I can't find where the [load_image(filename)](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/io/misc_io.py) function is called in the `application_driver.py`.

> I know the niftynet defines the [load_image(filename) function](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/io/misc_io.py) in `niftynet/io/misc_io.py`. However, I don't find how the `load_image` is called in promise 2012 demo.
> there is no `load_image` function in both [application_driver.py](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/engine/application_driver.py) and [segmentation_application.py](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/application/segmentation_application.py).

**Comment by EdwardMa12593** [comment]
A brief overview of NiftyNet components in the published paper.
![A brief overview of NiftyNet components](https://ars.els-cdn.com/content/image/1-s2.0-S0169260717311823-gr2.jpg)

**Comment by kwang-greenhand** [comment]
Yes in the application you call the sampler and load the image using Sampler's "pop_batch_op", instead of feeding data in "sess.run(variables, feed_data_dict = data_dict)".

Although I haven't found how the image augmentation is implemented...

**Comment by ericspod** [comment]
The `load_image` function is use in `image_type.py` ultimately in the implementation of `ImageFactory`. This is used eventually by `ImageReader` in `image_reader.py` which does the actual work of loading images and creating the image dictionary passed onto the network. In the application definitions `ImageReader` is instantiated for each set of input and stored in `self.readers`.
