### ISSUE TITLE
A strange number for Dice score in the training process

### ISSUE THREAD

**Issue by CourantNg** [NifTK/NiftyNet#38]
Dear all,
I use `Dice` as loss function and print the Dice score in the training process. Following is an example.
![Dice score](http://i1.bvimg.com/595387/58218e9803cf03b4.png)
![Dice score2](http://i1.bvimg.com/595387/f3bb6610d4c3465c.jpg)
However, the Dice scores of the foreground and background have a big gap. Normally, these two scores are very close.
Any explanation about this phenomenon will be very much appreciated.

**Comment by Zach-ER** [comment]
Hi there, 

Without much detail in this query, it's kind of hard to respond -- but I'll do my best! 

It seems like you're doing some sort of binary segmentation problem. What I guess could be happening is that the classes are highly unbalanced (i.e.  your images are predominantly background). In this case, it may be easy to get high dice scores on the background, and much harder to correctly identify the foreground. Could this be the case? 

What type of sampling are you using?

**Comment by CourantNg** [comment]
Dear @Zach-ER , thanks for your reply.
I try `Unet`, `Vnet`, `DenseVnet` with Dice loss function.
All the corresponding sampling type are `resize`. 
As you mentioned, the foreground and background are highly unbalanced. However, In the original `Vnet` paper, the experiments  showed `Dice`loss could overcome class imbalance compared with `mult. logistic loss`. So what's possible wrong with my parameter setting?

**Could you give me some advises to overcome the classes imbalance problem?**
Looking forward to your reply!
Best regards.

**Comment by Zach-ER** [comment]
Hi there, 

It could be a couple of things (off the top of my head). Firstly, 1500 or so training iterations might just be a small number -- is it still training at this time? What do the training curves look like in tensorboard? Maybe it will work with the current settings if given longer. 

With the 'resize' sampler you are using, what size are you 'resizing' the images to? It might be that it's better to use some other sampler (e.g. selective) that will maintain the image resolution. 

Other samplers you might like to use include the 'selective sampler', which will ensure that your image patches contain both foreground and background for it to train on.
