### ISSUE TITLE
spatial_window_size in promise12_demo_inference_config.ini

### ISSUE THREAD

**Issue by EdwardMa12593** [NifTK/NiftyNet#39]
Dear all,
In [NiftyNet/demos/PROMISE12/promise12_demo_inference_config.ini](https://github.com/NifTK/NiftyNet/blob/dev/demos/PROMISE12/promise12_demo_inference_config.ini), we can see `border = (5, 5, 5)` and `spatial_window_size = (0, 0, 3)`.  Why set these two parameters to these values? (the input `spatial_window_size` is `(64,64,64)` and the original image size is `(512*512*SliceNumber) `)

```python
[INFERENCE]
border = (5, 5, 5)
#inference_iter = 10
save_seg_dir = output/
output_interp_order = 0
spatial_window_size = (0, 0, 3)
```
The [documentation](https://github.com/NifTK/NiftyNet/tree/dev/config#inference) in `NiftyNet/config/` seems not enough to explain the setting of these two parameters. Would it be possible for you to add more explaination about these two parameters in the `inference` process?
For example, if I change the input spatial_window_size into `128*128*64` for Promise2012 dataset and want to obtain a `512*512*SliceNumber` output in the `inference` process,  what should the two parameters be?

Looking forward to your reply.

Best regards,
Edward

**Comment by wyli** [comment]
HI @EdwardMa12593 sorry for the confusion but the demo files are deprecating, please visit the model zoo (https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer/blob/master/dense_vnet_abdominal_ct_model_zoo.md) for the latest dense vnet model/config/demo data.
and there is better documentation on [readthedocs.io](http://niftynet.readthedocs.io/en/dev/config_spec.html#inference) we'll keep working on improving it.
