### ISSUE TITLE
Mixup / Mixmatch capability?

### ISSUE THREAD

**Issue by chazzmoney** [NifTK/NiftyNet#419]
Hello! I found your paper from MIDL 2018 on using mixup/mixmatch in semantic segmentation. In the paper, it mentioned that the code was viewable here - but I can't seem to find it. 

Is it present in one of the branches and I missed it?

Thanks!

**Comment by ericspod** [comment]
@Zach-ER Is there a link to the code somewhere?

**Comment by chazzmoney** [comment]
Thanks for looking - will be very helpful!

**Comment by Zach-ER** [comment]
Hi there, 

I have created a branch here: 
https://github.com/NifTK/NiftyNet/tree/419-add-mixup-mixmatch-from-MIDL-2018

That you can use while it pends merging into the main code. Two provisos: 

1. mixup is designed to be of low computational cost. My current implementation calls the sampler twice per iteration: if this is slow, it might be worth optimising further. 
2. mixup only works with dense losses (e.g. `Dice_Dense`). You may have to implement your own dense loss, although several are already there.

**Comment by chazzmoney** [comment]
I really appreciate it - thank you!
