### ISSUE TITLE
Why are the preprocessing layers deepcopied?

### ISSUE THREAD

**Issue by fepegar** [NifTK/NiftyNet#428]
I'd like to keep track of the random augmentation parameters applied to each single sample. Every time the reader is called, the [preprocessors are deepcopied](https://github.com/NifTK/NiftyNet/blob/df0f86733357fdc92bbc191c8fec0dcf49aa5499/niftynet/io/image_reader.py#L235-L244), therefore the information I want is not stored.

Why are these layers deepcopied before being randomised?

**Comment by fepegar** [comment]
It seems to work fine without the `deepcopy` operation.

**Comment by wyli** [comment]
Hi @fepegar because that function could be called from multiple threads simultaneously, deepcopy ensures the 'randomness'.

**Comment by fepegar** [comment]
Thanks @wyli
