### ISSUE TITLE
crop_kernel size in 3D unet

### ISSUE THREAD

**Issue by EdwardMa12593** [NifTK/NiftyNet#44]
Dear NiftyNet team:
I print the size of every layer output in [unet](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/network/unet.py) (line 121).  It's strange, the 'crop_kernel' size has a different format compared to the input size.
![Markdown](http://i2.bvimg.com/595387/1c44eadac6113765.jpg)

Would it be possible for you to give me some explanation about the size of `crop_kernel`?
Best regards,
Edward

**Comment by wyli** [comment]
please see #17
