### ISSUE TITLE
How does the mask operation work? Train with Image/Label/Mask and test only with "image".

### ISSUE THREAD

**Issue by maz369** [NifTK/NiftyNet#441]
Hello,

I am wondering how is the mask used during training and inference with Niftynet. Is this based on ROI pooling? I also appreciate if you could let me know which .py file incorporate the mask. I have been searching through Niftynet Python modules but could not find it.
Also, is there any way to train a model with "image", "label" and "mask" but perform inference only on "image". There are instances that the label and mask for validation sets are not available and we have access only to the image and need to submit the result to a third party.
Thanks for your help.

**Comment by wyli** [comment]
Hi @maz369 you can remove the line of config `label=...` in section `[segmentation]` during inference
