### ISSUE TITLE
GPU->CPU Memcpy failed (pip version of tensorflow)

### ISSUE THREAD

**Issue by IsaacLord** [NifTK/NiftyNet#445]
I'm trying to use  3D network by using GPU (2080 Ti), however i got following error.

GPU->CPU Memcpy failed 

2019-10-01 11:06:06.793519: I tensorflow/stream_executor/stream.cc:5011] [stream=00000256E1A01E70,impl=00000256E5F61A70] did not memcpy device-to-host; source: 0000000B11880D00
2019-10-01 11:06:06.791243: F tensorflow/core/common_runtime/gpu/gpu_util.cc:292] GPU->CPU Memcpy failed

even with spatial window (8,8,8) by batch size=1.

is there any idea how to fix this?

**Comment by IsaacLord** [comment]
Just change the Tensorflow Version!

**Comment by wyli** [comment]
thanks @DeepMedi  probably https://github.com/NifTK/NiftyNet/blob/dev/requirements-gpu.txt#L6 needs to be revised due to some recent changes in tensorflow's pip package

**Comment by talmazov** [comment]
> Just change the Tensorflow Version!

What tensorflow version and numpy did you use? i have niftynet 0.6, CUDA 10.0, tensorflow-gpu 1.13.2 and numpy 1.16
using geforce RTX 2060 6GB vram with nvidia driver 440.33.01

Still doesn’t work...
