### ISSUE TITLE
Support for tensorflow 1.15

### ISSUE THREAD

**Issue by tvercaut** [NifTK/NiftyNet#459]
Compatibility with TF 1.1.5 needs to be confirmed.

Additionally, it would probably be good to make TF 1.15 the default backend for tensorflow. Indeed, we can read that 
> For the 1.15 release, CPU and GPU support are included in a single package

https://www.tensorflow.org/install/pip?lang=python3

This should simplify installation requirements notably by allowing to merge
https://github.com/NifTK/NiftyNet/blob/dev/requirements-cpu.txt
https://github.com/NifTK/NiftyNet/blob/dev/requirements-gpu.txt

**Comment by danieltudosiu** [comment]
I will take this issue.

**Comment by danieltudosiu** [comment]
Note, it requires cudnn 7.6
