### ISSUE TITLE
NiftyNet need new logo and some style. 

### ISSUE THREAD

**Issue by andrejcibik** [NifTK/NiftyNet#48]
Hello,
this my logo design for your project. Its free, created on Utopian platform where users are rewarded for contributions to open-source projects. You dont have to agree on anything or pay anything, its free to use, just like your code. 

https://busy.org/@andrejcibik/niftynet-logo-open-source-convolutional-neural-networks-platform

![niftynet-thumb.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517916805/holm9u9pdnctd1vsiy0s.jpg)

**Comment by tvercaut** [comment]
To ease the discussion, I am copying the alternative suggestion made in #59 by @Colmena-PM:

> https://steemit.com/utopian-io/@colmena-powmax/logo-designs-for-niftynet
> 
> ![nifftynet](https://user-images.githubusercontent.com/36889309/36732387-fb96c9d2-1ba3-11e8-8cea-657aff76cc4b.jpg)

**Comment by dzhoshkun** [comment]
I'd like to thank @Colmena-PM and @andrejcibik for their designs.

Comments to @andrejcibik's design:
- I like the simplicity of this logo.
- The colours could be a bit more prominent and shiny. Or maybe black can be used for "NiftyNet" as well as the two triangular / shadowy shapes?
- The shape to the left looks a bit too random to me. How does it relate to NiftyNet?
- The colours look "speckled". Is that deliberate?
- The font of "NiftyNet" is edgy while the shape is not.

Comments to @Colmena-PM's design:
- The colour is catchy, but causes a bit of strain to the eyes.
- Also I'm not sure how well it will play with other logos, for instance on a PowerPoint slide.
- The "font" of the "N" in the logo does not match that of the N's in "NiftyNet"
- I assume the second shape in the logo is an "N" as well? However this is not immediately clear, and a bit confusing. Also, I can't relate the components that make up that second "N" to anything relevant to NiftyNet.

**Comment by andrejcibik** [comment]
If just a styled brain :) "specs" and shadows are just part of the presentation :) Thank you for feedback anyways. 

If you would like all user on Utopian to "compete" to make you a new design, you can register and createso called "Task request"..... for free :)

**Comment by wyli** [comment]
more ideas @ utopian.io: 
https://utopian.io/project/NifTK/NiftyNet/github/101853569/all

**Comment by tvercaut** [comment]
Copying proposal from @moenawar85 in #64 for convenience.

> Hello,
this my logo design for your project. Its free, created on Utopian platform where users are rewarded for contributions to open-source projects. If you like it, spread the good work about the platform.
![nifty net logo final](https://user-images.githubusercontent.com/36834147/37575217-8a0d1342-2b58-11e8-8c47-830c6ed3838f.jpg)

**Comment by nasirparwaz** [comment]
Can I contribute new logo design for Nifty Net??

**Comment by tvercaut** [comment]
We need to revive this. Also just saw that the logo of Subtle Medical is somehow similar to the first one proposed in this thread: https://www.linkedin.com/company/subtlemedical/

**Comment by mmodat** [comment]
@tvercaut @mjorgecardoso What are we doing here? It has been open for 1 year and no action. Closing for now?

**Comment by tvercaut** [comment]
@mmodat No, this is still open.

**Comment by tvercaut** [comment]
NiftyNet is now unmaintained. This issue can thus be closed.
