### ISSUE TITLE
error: argument --axcodes: list of strings expected

### ISSUE THREAD

**Issue by josemariamoreira** [NifTK/NiftyNet#49]
I have just started exploring NiftyNet, which I think will help me in my project.

I am trying to train a network for segmentation using the segmentation_application. However I built my own config.ini file and when running net_run.py I receive the error:

> error: argument --axcodes: list of strings expected, for each list element the allowed characters: [ a-zA-Z0-9_\-], but received ' ' 

I am following the configuration file requirements setting `axcodes=A,R,S`. I also tried different lists of strings ('A','R','S'; [A,R,S]; (A,R,S); ...)

My config.ini file states:

`[T2]`
`csv_file = /home/jose/niftynet/data/uNet/test_data/data_file.csv`
`spatial_window_size = (257,257,30)`
`pixdim = (1.0, 1.0, 1.0)`
`axcodes= A,R,S`
`interp_order=1`

What am I doing wrong?

**Comment by wyli** [comment]
HI @josemariamoreira if there's something like `axcodes=''` in your code, remove that line should work

**Comment by josemariamoreira** [comment]
The problem was in the [parcellation] section... Wasn't looking there... Thanks!
