### ISSUE TITLE
Using Multiple GPU Fails ? 

### ISSUE THREAD

**Issue by ahatamiz** [NifTK/NiftyNet#50]
When I run the net_segment with dense_vnet on my data, everything works perfectly on a single GPU. However, specifying more than 1 GPU throws the following error: 

 InvalidArgumentError (see above for traceback): Duplicate tag imgseg/image/0 found in summary inputs
	 [[Node: MergedOutputs/Merge/MergeSummary = MergeSummary[N=3, _device="/job:localhost/replica:0/task:0/cpu:0"](worker_0/DenseVNet/PyFunc, worker_1/DenseVNet/PyFunc, MergedOutputs/loss_device_average_)]]
	 [[Node: ApplyGradients/Mean_44/_2581 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_49819_ApplyGradients/Mean_44", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Any idea what is wrong ?

**Comment by wyli** [comment]
Thanks @ahatamiz for the feedback. looks like the current tensorboard visualisation of dense_vnet is not compatible with the multi-gpu option, a temporary solution would be removing the visualisation by commenting out line 273 to line 293 of the dense vnet code https://github.com/NifTK/NiftyNet/blob/dev/niftynet/network/dense_vnet.py#L273 

A permanent solution would be removing duplicated tags in `tf.GraphKeys.SUMMARIES`  collection and printing a warning message before this call: https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/blob/dev/niftynet/engine/application_variables.py#L188 @eligibson what do you think?

**Comment by eligibson** [comment]
I think removing duplicate tags generated by additional GPUs (when they are not being averaged) before merging makes sense at first glance.

I also think that those summaries (which are application-specific, but not network-specific) should probably be moved out of the network code (maybe into the application in some form).

**Comment by ahatamiz** [comment]
Problem solved. Thanks @wyli  @eligibson

**Comment by wyli** [comment]
Thanks both, I've created a new ticket for this https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/issues/251
