### ISSUE TITLE
net_download fail

### ISSUE THREAD

**Issue by yenhochen** [NifTK/NiftyNet#53]
I'm currently trying to try out the `net_download` command, but I am getting the following error.

```
Accessing: https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer
Warning: updating the examples file from the server caused an error: [Errno socket error] [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:661)
highres3dnet_brain_parcellation_model_zoo: FAIL.
Cannot download the examples configuration file. Is the server down?
```
What can I do?

**Comment by WellerCao** [comment]
I also encountered the same problem when using net_download, are you Chinese?  I think it may be because of our network.

**Comment by EdwardMa12593** [comment]
try to climb over the wall

**Comment by 1160914483** [comment]
Create discussion groups from Chinese niftyNet users, please join QQ:684027141
