### ISSUE TITLE
spatial_window_size Question

### ISSUE THREAD

**Issue by yenhochen** [NifTK/NiftyNet#54]
In the Input Data section of the Configuration file, does `spatial_window_size` refer to the sliding convolution window? If not, then what exactly is it referring to? 

Also, why do the values have to be a multiple of 8 when using some of the applications (e.g. VNet, UNet)?

Thanks

**Comment by Zach-ER** [comment]
It tells NiftyNet how big a patch to load in at a time. 

For the multiples of 8, this is normally because for multi-scale approaches, it will allow the patches to be stacked without padding.

**Comment by josemariamoreira** [comment]
Hi! 
A few more question on this:
1. how does Niftynet choose which patch of the image to analyze (meaning which location)? is it random in each input image?
2. in each iteration (and considering that batch_size is 1), Niftynet will only find the features that explain that one patch with 'spatial_window_size' dimensions? 
3. when batch_size is more than 1, will it select patches from different inputs? or from the same input image?

thanks in advance!

**Comment by 1160914483** [comment]
Is your problem solved?
