### ISSUE TITLE
NiftyNetExamples server is not running

### ISSUE THREAD

**Issue by cedwards77** [NifTK/NiftyNet#55]
When executing the following command on my MacBookPro (macOS High Sierra v. 10.13.3):
    net_download highres3dnet_brain_parcellation_model_zoo

this message is displayed:
   Accessing: https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer
   The NiftyNetExamples server is not running

When I run the same command on an Ubuntu stand-alone server and on an EC2 instance it works fine.  A previous post mentioned this same issue in the context of an SSL connection error, but it seemed to be resolved.  Is this a problem for macOS? Is there something I need to do on my end to fix it?  

Thank you!

**Comment by BohriumKwong** [comment]
I run the command twice,no matter on Win10 or Ubuntu 16.04, it dose not work. I see the code in ‘download.py’:
`    any_error = False
    for example_id in example_ids:
        if not example_id:
            any_error = True
            continue
        if config_store.exists(example_id):
            update_ok = config_store.update_if_required(
                example_id,
                download_if_already_existing)
            any_error = (not update_ok) or any_error
        else:
            any_error = True
            if server_ok:
                print(example_id + ': FAIL. ')
                print('No NiftyNet example was found for ' + example_id + ".")

    # If errors occurred and the server is down report a message
    if any_error and not server_ok:
        print("The NiftyNetExamples server is not running")

    return not any_error`
I can not find the reason why the value of 'any_error' is not true when 'https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer' can be accessed by browser.

**Comment by skyuuka** [comment]
I have the same issue, and my NiftyNet version is 0.5.0
