### ISSUE TITLE
Tensorflow 1.4 Issues

### ISSUE THREAD

**Issue by yenhochen** [NifTK/NiftyNet#56]
I need to use tensorFlow 1.4 for our HPC GPUs since Tensorflow 1.3 isn't fully supported, I noticed that I needed to comment out lines 468-470 in `<niftynet.layer.resampler.py>` to get the PROMISE12 demo working.

```
@tf.RegisterGradient('FloorMod')
def _floormod_grad(op, grad):
    return [None, None]
```

What other changes do I need to make to make NiftyNet compatible with tensorflow1.4?

**Comment by wyli** [comment]
I think that's it, please let us know if you run into any issues and feel free to reopen this ticket.
