### ISSUE TITLE
Creating config_dir even when config file is passed

### ISSUE THREAD

**Issue by JoaoSantinha** [NifTK/NiftyNet#61]
Hi,

I am trying to run dense_vnet training on HTCondor cluster. I am providing a configuration file that I copied from the original configuration file and made changes on the dirs and num_classes to adapt to my problem.

I don't have write access were the training is running and I was checking were it fails and it is failing on the following line https://github.com/NifTK/NiftyNet/blob/f2aeefb9eae37ae765f20189927b7a5059c57834/niftynet/utilities/niftynet_global_config.py#L120

From my understanding when the **NiftyNetGlobalConfig setup()** is called and will assume that the **self._config_home** is always **~/.niftynet** regardless if a config file is passed and then on **__load_or_create(self._config_file)** it will try to create the dir **~/.niftynet** instead of loading the provided config file. Is this done on purpose? Would it be possible to change this behaviour and actually set the right **self._config_home** to the provided config file so it is loaded insteady of creating the **~/.niftynet** dir and a default **config.init** inside?

Let me know if any other information is necessary.

Thanks,
Joao

**Comment by wyli** [comment]
Hi @JoaoSantinha I think you're right, ``self._config_home`` is always ``~/.niftynet`` as in https://github.com/NifTK/NiftyNet/blob/f2aeefb9eae37ae765f20189927b7a5059c57834/niftynet/utilities/niftynet_global_config.py#L32

@dzhoshkun  Shall we change this to use a ``$niftynet_config_home`` variable from the user's environment? 

So that the config home can be redirected, for example:
```bash
export niftynet_config_home=some/other/path; net_segment train ...
```

**Comment by wyli** [comment]
`self._config_home` now reads `$niftynet_config_home ` if defined

**Comment by JoaoSantinha** [comment]
Thank you very much @wyli and @dzhoshkun and congratulations to the NiftyNet team for the awesome work!!!
