### ISSUE TITLE
rename_crop_BRATS.py isn't working for BraTS2015 dataset

### ISSUE THREAD

**Issue by sabrinamusatian** [NifTK/NiftyNet#62]
When trying to convert the dataset downloaded from  https://sites.google.com/site/braintumorsegmentation/home/brats2015 there is an assertion error, caused in function load_scans_BRATS15. I expected the code and it seems that the problem is caused by the fact that the images in original dataset are in .mha, but load_scans_BRATS15 expect to read .nii images. This logic works fine for BraTS2017 dataset since they are in .nii format from the beginning. However, 2015 seems to need some fixing.

**Comment by wyli** [comment]
Thanks for the feedback! The script is now updated to load `.mha`s, `SimpleITK` needs to be installed in advance.
