### ISSUE TITLE
Task Request; New logo NiftyNet Proposal

### ISSUE THREAD

**Issue by moenawar85** [NifTK/NiftyNet#64]
Hello,
this my logo design for your project. Its free, created on Utopian platform where users are rewarded for contributions to open-source projects. If you like it, spread the good work about the platform.
![nifty net logo final](https://user-images.githubusercontent.com/36834147/37575217-8a0d1342-2b58-11e8-8c47-830c6ed3838f.jpg)

**Comment by tvercaut** [comment]
Merging this into issue #48 as a duplicate
