### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by yenhochen** [NifTK/NiftyNet#65]
I'm trying to do a 3d image regression using NiftyNet and the highres3dnet, but I am getting the following error.

> InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,1,80,1] rhs shape= [1,1,80,1]

The error is traced back to 

>   File "/.conda/envs/Greens/lib/python2.7/site-packages/niftynet/engine/application_driver.py", line 256, in run_application
>     self.graph = self._create_graph(self.graph)
>   File "/.conda/envs/Greens/lib/python2.7/site-packages/niftynet/engine/application_driver.py", line 357, in _create_graph
>     save_relative_paths=True)

what can I do?

**Comment by sia79** [comment]
I had a similar error as well. In my case I could solve it when changing the dimension in the header of the input .nii file
from
    dim             : [  3 448 448 210   0  0  0   0] 
to 
    dim             : [  3 448 448 210   1   1   1   1]

**Comment by wyli** [comment]
Thanks @sia79! This is now fixed by https://github.com/NifTK/NiftyNet/commit/e5c7a8dee18483c86a7e708c9d8b535c581dcd6a.
