### ISSUE TITLE
3D image regression

### ISSUE THREAD

**Issue by yenhochen** [NifTK/NiftyNet#67]
I was looking at your 2d image mr_ct_regression example and was wondering if you guys had a 3d implementations of it.

**Comment by mjorgecardoso** [comment]
Yes, the net_regress.py application with the default_monomodal_regression.ini configuration file provided under /config will do 3D MR->CT semantic regression by sampling patches of size [64,64,64]

**Comment by yenhochen** [comment]
Do you have the 3d MRI/CT data available for this? I can only seem to find the 2d data
