### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by yenhochen** [NifTK/NiftyNet#68]
Hi,

Is it possible to create reproducible results by setting a random seed for the same initialization in niftynet? and if so, how would I do it? Are there any other parameters to set to ensure reproducibility?

Thanks,
Yenho

**Comment by wyli** [comment]
Hi @yenhochen that's not implemented yet, 'adding an option for the dropout layer (https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/issues/242)' is on the todo list. We'll also add functionalities for fixed random seeds to make it 'less random', but some cuda ops are still non-deterministic (https://github.com/tensorflow/tensorflow/issues/3103).

**Comment by yenhochen** [comment]
I noticed that you are able to save checkpoints in the network weights. If I save a model.ckpt file at the 0th iteration and I copy the same file over to other models where I set the starting iteration to -1, would I get the same initialization?

**Comment by wyli** [comment]
Yes, with `--max_iter 0 --starting_iter 0`, the model will be saved at the 0-th iter, and `--starting_iter -1` would load the initialisation.

**Comment by yenhochen** [comment]
Is it possible to see the initiaized weights. I tried opening the model.cpkt files in notepad and it doesn't seem to be readable.

**Comment by mmodat** [comment]
@yenhochen Apologies for the "belated" answer. You can export them to tensorboard should you want to.
Closing this issue as it has been addressed by merge 261 addressing #242.
