### ISSUE TITLE
is pre_trained model avaliable for download?

### ISSUE THREAD

**Issue by qianyizhang** [NifTK/NiftyNet#7]
Also, have you run the implemented networks and compare the results against original paper's benchmark?
It's also very interesting to see the limit of [batch_size, input_size] for each network at given GPU memory.

great work overall, cheers!

**Comment by wyli** [comment]
Hi @qianyizhang many thanks for the feedback, we're setting up a 'model zoo' https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/issues/192 and are testing the workflow for model downloading -- as a starting point we implemented a downloading workflow and a few pre_trained models, they'll be available soon.

For your second question, at the moment we haven't tried to replicate the results of each paper yet. Always welcome contributions on this topic :)

In terms of GPU memory, there's functionality to count number of trainable parameters, https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/blob/dev/niftynet/layer/base_layer.py#L75 
Accurate memory profiling was not straightforward for earlier versions of tensorflow, but it seems that's not the case now https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/profiler we'll look into that.
