### ISSUE TITLE
Net_regression and masking

### ISSUE THREAD

**Issue by yenhochen** [NifTK/NiftyNet#70]
For the niftynet net_regression, is there any documentation on how the masking works? Does the network only sample within the mask? and how?

**Comment by mjorgecardoso** [comment]
The data passed to the "[REGRESSION] weight" will only act on the loss function (just a pixel wise multiplication of the loss). 

To restrict the sampling to the masked area, the same data needs to be passed to "[REGRESSION] sampler", and the sampler has to be set to "window_sampling=weighted". The sampler will then sample from pixel-centered patches with frequency equal to the pixel values in the data assigned to "[REGRESSION] sampler", e.g. if you give it a binary mask, pixels outside of the mask will have a frequency of 0 (no sampling), while pixels inside the mask will have a frequency of 1. 

Note that frequencies do not need do be binary. See here: http://niftynet.readthedocs.io/en/dev/_modules/niftynet/engine/sampler_weighted.html?highlight=window_sampling

**Comment by nouranik** [comment]
thank you for the guidance,
I have a ground truth a volume that in the center the intensities are larger and more important than the peripheral part. I provided the volume matrix (weight) to improve the quality of prediction but it did not make the result better at all. what would you suggest?
