### ISSUE TITLE
mr_ct_regression inclusion/exclusion criteria

### ISSUE THREAD

**Issue by yenhochen** [NifTK/NiftyNet#74]
Hi, do you know the inclusion exclusion criteria for the subjects used in this example. For example, were the subjects all adults? all male or female? Did these images contain abnormalities or are they all healthy subjects?

**Comment by mjorgecardoso** [comment]
Do you mean the example on the NiftyNet paper? They are healthy and demented subjects, M/F balanced, ages 60+, part of the AVID dataset (the same as used in Burgos et al. TMI 2014)
