### ISSUE TITLE
How do I get the best inference results

### ISSUE THREAD

**Issue by yenhochen** [NifTK/NiftyNet#75]
Hi,

I noticed that I get different image results given by changing the spatial_window_size in the Inference section of a 3d image regression. Depending on the window size, my niftynet inference output might be striped in different axes. How do I set it up so that I get the best result for my niftynet inference output?

![727272](https://user-images.githubusercontent.com/12815796/38261790-e941bea6-3730-11e8-9325-e0ef8f18dd8f.PNG)
spatial_window_size=(72,72,72)

![16128128](https://user-images.githubusercontent.com/12815796/38261815-f8da0814-3730-11e8-992a-508c70612dda.PNG)
spatial_window_size=(16,128,128)

![646464](https://user-images.githubusercontent.com/12815796/38261819-fb6a88c4-3730-11e8-956a-8b85b72ab724.PNG)
spatial_window_size=(64,64,64)

**Comment by wyli** [comment]
Hi @yenhochen setting `border` (http://niftynet.readthedocs.io/en/dev/config_spec.html#border) to larger values might be helpful.
