### ISSUE TITLE
PROMISE12-demo: incorrect inference size

### ISSUE THREAD

**Issue by amh28** [NifTK/NiftyNet#81]
Hello, I have trained the vnet using the promise dataset, without modifying any part of the network using spatial_window_size = (64, 64, 64) . However, when I do inference over the trained model, the resulting volumes are resized to a completely different resolution, as shown in this image:  
[https://drive.google.com/file/d/1J2EE36LqLSPImam1TyQMbtX24MFEpaJw/view?usp=sharing](url)

**These are the .config files used for training and inference:**

************ **CONFIG FILE FOR TRAINING** *******************

[promise12]
path_to_search = data/PROMISE12/TrainingData_Part1,data/PROMISE12/TrainingData_Part2,data/PROMISE12/TrainingData_Part3
filename_contains = Case,mhd
filename_not_contains = Case2,segmentation
spatial_window_size = (64, 64, 64)
interp_order = 3
axcodes=(A, R, S)

[label]
path_to_search = data/PROMISE12/TrainingData_Part1,data/PROMISE12/TrainingData_Part2,data/PROMISE12/TrainingData_Part3
filename_contains = Case,_segmentation,mhd
filename_not_contains = Case2
spatial_window_size = (64, 64, 64)
interp_order = 0
axcodes=(A, R, S)

############################## system configuration sections
[SYSTEM]
cuda_devices = ""
num_threads = 2
num_gpus = 1
model_dir = ./promise12train_vnetdice
[NETWORK]
name = vnet
activation_function = prelu
batch_size = 1
volume_padding_size = 0
histogram_ref_file = standardisation_models.txt
norm_type = percentile
cutoff = (0.01, 0.99)
normalisation = True
whitening = True
normalise_foreground_only=True
foreground_type = otsu_plus
multimod_foreground_type = and
window_sampling = resize
queue_length = 8

[TRAINING]
sample_per_volume = 4
rotation_angle = (-10.0, 10.0)
scaling_percentage = (-10.0, 10.0)
scaling_percentage = (-10.0, 10.0)
random_flipping_axes= 1
lr = 0.00001
loss_type = Dice
starting_iter = 0
save_every_n = 500
max_iter = 10000
max_checkpoints = 20
validation_every_n = 100
exclude_fraction_for_validation = 0.3
tensorboard_every_n = 100

[SEGMENTATION]
image = promise12
label = label
output_prob = False
num_classes = 2
label_normalisation = True
min_numb_labels = 2
min_sampling_ratio = 0.000001

************ **CONFIG FILE FOR INFERENCE** *******************
[promise12]
csv_file = file_list_inference.csv
#filename_contains = Case2,mhd
#filename_not_contains = segmentation
spatial_window_size = (64, 64, 64)
interp_order = 3
axcodes=(A, R, S)

[label]
csv_file = file_list_inference_seg.csv
#filename_contains = Case2,_segmentation,mhd
#filename_not_contains =
spatial_window_size = (64, 64, 64)
interp_order = 0
axcodes=(A, R, S)

############################## system configuration sections
[SYSTEM]
cuda_devices = ""
num_threads = 2
num_gpus = 1
model_dir = ./promise12train_vnetdice
[NETWORK]
name = vnet
activation_function = prelu
batch_size = 1
volume_padding_size = 0
histogram_ref_file = standardisation_models.txt
norm_type = percentile
cutoff = (0.01, 0.99)
normalisation = True
whitening = True
normalise_foreground_only=True
foreground_type = otsu_plus
multimod_foreground_type = and
window_sampling = resize
queue_length = 8

[TRAINING]
sample_per_volume = 4
rotation_angle = (-10.0, 10.0)
scaling_percentage = (-10.0, 10.0)
random_flipping_axes= 1
lr = 0.00002
loss_type = Dice
starting_iter = 0
save_every_n = 500
max_iter = 4000
max_checkpoints = 20
validation_every_n = 100
exclude_fraction_for_validation = 0.3
tensorboard_every_n = 100
#reg_type = L1
#eexclude_fraction_for_inference = 0.1

[INFERENCE]
#border = (0,0,0)
save_seg_dir = output4000/
output_interp_order = 0
spatial_window_size = (0,0,3)

############################ custom configuration sections
[SEGMENTATION]
image = promise12
label = label
output_prob = False
num_classes = 2
label_normalisation = True
min_numb_labels = 2
min_sampling_ratio = 0.000001

Any ideas why this is failing?
Thanks for the support.

**Comment by mjorgecardoso** [comment]
Your inference spatial_window_size is too small and the network has no field off view.

Just set in the [INFERENCE] block:
spatial_window_size = (80,80,80)
border = (8,8,8)

**Comment by amh28** [comment]
Hi, I just tried changing to some other different spatial_window_size, including the one you suggested but nothing changed. This behavior is strange, since for this experiment I didn't change any part of the implementation and I am basically using the same .config file provided in the demos section. I don't understand why the net is not doing the proper resize to the output dimensions that I provide.
