### ISSUE TITLE
'balanced' window sampling

### ISSUE THREAD

**Issue by RayJkl** [NifTK/NiftyNet#86]
Hi, it seems to me that the 'balanced' window sampling is not ready to be used yet. When can we expect to use it? Thanks!

**Comment by wyli** [comment]
Hi @RayJkl @YilinLiu97  'balanced' sampling option was not included in the config parser earlier, now it's fixed.  

To use the sampler, additional sampling map needs to be specified with `sampler=...` in the `[segmentation]` section: https://github.com/NifTK/NiftyNet/blob/92ce865143fb998e19f6715b2a673a0aba94b7da/demos/PROMISE12/promise12_balanced_train_config.ini#L59-L61
This example uses the training label section`[label]` in the config file as the sampling prior.

Finally to run the segmentation application: 

```
python net_segment.py train --window_sampling balanced -c ...
```
