### ISSUE TITLE
'Inference' is saving outputs without complete names

### ISSUE THREAD

**Issue by josemariamoreira** [NifTK/NiftyNet#87]
Hi,

I've been running inferences from the networks I have been training. On my output folder I have all the network outputs, however they are saved with incomplete names that prevent me from correctly identifying from which input image it was inferred from.

Here is an example:

on my config file I have:
[Dyn]
path_to_search = C:\Users\josemaria\Documents\Ze\DynData\Testing
filename_contains = Dyn

this path contains several images with this type of name (I will just give one example for simplicity):
2004Dyn_257.nii
(patient number + Dyn_ + slice number)

On the .csv saved while inference is running, I find:
   A   |     B
_257 | C:\Users\josemaria\Documents\Ze\DynData\Testing\2004Dyn_257.nii

Leading to the output file:
_257_niftynet_out.nii

I would expect that inference would search for 'Dyn' and the file would be identified as 2004_257. Strangely this happens just in some cases. In the some run I have some file with the correct name and others like I explained above. I couldn't identify the pattern in the error.

This is a problem when I have two or more patients with the same slice number.

I hope that you can help me with this.

**Comment by wyli** [comment]
Hi @josemariamoreira 

Have you checked the `Dyn.csv` file in the `model_dir`, it should contain a table of `unique_id, filename`. As long as the files can be uniquely identified by those automatically extracted ids, I think the issue reported here is not an urgent one (please let us know if that's not the case).

At the moment, to extract unique id from a filename, the name e.g. `2004Dyn_257.nii` is decomposed  into candidates `[2004, _257, 2004_257]` based on `filename_contains = Dyn`, and one candidate will be selected (in a greedy manner) if it's a common id for multiple files of the subject and doesn't conflict with the others.

**Comment by josemariamoreira** [comment]
Hi @wyli 

You are right! If I have patients with the same slice number, the names will be assigned as an unique id (`2004_257_niftynet_out.nii` and `5993_257_niftynet_out.nii`). 

Thanks for your nice work!
