### ISSUE TITLE
Elongate the deepmedic network

### ISSUE THREAD

**Issue by RocketRollxx** [NifTK/NiftyNet#88]
Hi, I want to elongate the deepmedic network so I added a few more numbers in the variable 'self.conv_features' in deepmedic.py. 

E.g., 

> self.conv_features = [30,30,40,40,40,40,50,50] --> [30,30,40,40,40,40,50,50,50,50]

But I got this error message:
`
ValueError: Dimension 1 in both shapes must be equal, but are 7 and 3. Shapes are [10,7,7,7] and [10,3,3,3]. for 'worker_0/DeepMedic/residual_concat/concat' (op: 'ConcatV2') with input shapes: [10,7,7,7,50], [10,3,3,3,50], [] and with computed input tensors: input[2] = <-1>.

originally defined at:
  File "/home/RR/Niftynet/niftynet/layer/elementwise.py", line 31, in __init__
    super(ElementwiseLayer, self).__init__(name=self.layer_name)
  File "/home/RR/Niftynet/niftynet/layer/base_layer.py", line 58, in __init__
    super(TrainableLayer, self).__init__(name=name)
  File "/home/RR/Niftynet/niftynet/layer/base_layer.py", line 26, in __init__
    self._op = tf.make_template(name, self.layer_op, create_scope_now_=True)
  File "/home/RR/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 153, in make_template
    **kwargs)
`
I guess that this has to do with the output size after upsampling..

Thanks so much!

**Comment by RayJkl** [comment]
I have the same issue!! also waiting for an answer

**Comment by mmodat** [comment]
In the deepmedic framework, the two paths must end with patches of similar spatial sizes. By using the "VALID" option in the convolution layer, adding new layers will break this consistency. You have to calculate the required initial patch size (and associated number of layers) to make this possible.
