### ISSUE TITLE
Flipped labels lead to weird imblanced class prediction

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#90]
Hi, I have a super weird problem: I have 3 classes, including the background (i.e., 0,1,2). Previously I always assigned 1 to a tissue on the left and 2 to the one on the right, and it seemed to work just fine. Recently, I flipped the two labels, i.e., 2 to the tissue on the left and 1 to the one on the right, and the weird thing happened: it did "identified" the two tissues, but always assigned the same label to both classes, i.e., either both of them are 1 or 2, which never happened before flipping the labels. 

**More info**: I used the same dataset, same network even same hyperparameters. The problem is imblanced so I used "balanced" sampler. They were trained from the scratch. 

Any help would be appreciated!!

**Comment by wyli** [comment]
Hi @YilinLiu97 is it possible that you only flipped labels for some of the training volumes? have you checked the probability outputs?
