### ISSUE TITLE
How to Access The Numpy Version of the Image

### ISSUE THREAD

**Issue by yufeihun** [NifTK/NiftyNet#91]
After the inference is done on the image, what's a good way of accessing the numpy version of the image ( since NiftyNet already converts ) and save it ?

**Comment by 1160914483** [comment]
Hello, are you Chinese? Do you have time to tell me how to enter any size image?

**Comment by wyli** [comment]
Hi @yufeihun it's in NIfTI format, one option would be using NiBabel (http://nipy.org/nibabel/nibabel_images.html#getting-the-image-data-the-easy-way):
```python
import nibabel
numpy_array = nibabel.load_data('image.nii.gz').get_data()
```
