### ISSUE TITLE
Input window size of 3D U-net 

### ISSUE THREAD

**Issue by 1160914483** [NifTK/NiftyNet#93]
I cannot freely determine the size of the input image. It seems that the size must be based on these constraints（Unet）:
           assert layer_util.check_spatial_dims(images, lambda x: x % 8 == 0)
           assert layer_util.check_spatial_dims(images, lambda x: x >= 89)

My data image size is (240,240,155), and when I use it as spatial_window_size, it reports an error:
       ValueError: input tensor's spatial dimensionality not not compatible, please tune the input window 
       sizes: assert layer_util.check_spatial_dims(images, lambda x: x % 8 == 0)

However, when I chose (240,240,96) as the spatial_window_size, it complaints that:

     ValueError: Dimension size must be evenly divisible by 184832 but is 5529600 for 
     'worker_0/loss_function/Reshape_1' (op: 'Reshape') with input shapes: [240,240,96,1], [2] and with 
      input tensors computed as partial shapes: input[1] = [184832,?].

I want to know how we should handle this issue.

**Comment by Zach-ER** [comment]
I'm not entirely sure what the problem is here. Could you tell us what the `spatial_size` is for the label that you're using? Also, could you try a cubic window e.g. `(152, 152, 152)`.

**Comment by 1160914483** [comment]
Thank you very much for your reply. I resize the data size to (120*120*120) and change the label size to (32*32*32).The problem was solved.

**Comment by 1160914483** [comment]
Thank you very much for your reply. I resize the data size to (120*120*120) and change the label size to (32*32*32).The problem was solved.

**Comment by Zach-ER** [comment]
@wyli or @1160914483 could you please mark as closed :)
