### ISSUE TITLE
Revise contribution guide after deprecating CmicLab

### ISSUE THREAD

**Issue by dzhoshkun** [NifTK/NiftyNet#98]
The [contribution guide](https://github.com/NifTK/NiftyNet/blob/dev/CONTRIBUTING.md#merging-github-pull-requests) still mentions Cmiclab as the main dev hub. However this is misleading as we have decided to deprecate CmicLab in favour of GitHub. We therefore need to revise this information, and push it onto GitHub as soon as possible.

@wyli any other item you can think of that needs to be revised?

**Comment by wyli** [comment]
Yes, some misc. items in addition to https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/issues/269:
- [ ] there's a copy of the same guide on documentation website [change the template here](https://github.com/NifTK/NiftyNet/blob/dev/doc/source/contributing.md).

- [ ] replicate the cmiclab wiki to this repo, mainly meeting minutes

- [ ] creating/tracking milestones with [GitHub's project tab](https://github.com/NifTK/NiftyNet/projects)?
